/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Order Management
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property chargeableCheckedBags Details of chargeable checked bags
 * @property chargeableSeatNumber seat number
 * @property otherServices Other services to add
 */
@JsonClass(generateAdapter = true)
data class AdditionalServicesRequest(
    @Json(name = "chargeableCheckedBags") @field:Json(name = "chargeableCheckedBags") var chargeableCheckedBags: BaggageAllowance? = null,
    @Json(name = "chargeableSeatNumber") @field:Json(name = "chargeableSeatNumber") var chargeableSeatNumber: String? = null,
    @Json(name = "otherServices") @field:Json(name = "otherServices") var otherServices: List<ServiceName>? = null
)
