/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Order Management
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
* additional service type
* Values: CHECKED_BAGS,MEALS,SEATS,OTHER_SERVICES
*/
@JsonClass(generateAdapter = false)
enum class AdditionalServiceType(val value: String) {
    @Json(name = "CHECKED_BAGS") CHECKED_BAGS("CHECKED_BAGS"),
    @Json(name = "MEALS") MEALS("MEALS"),
    @Json(name = "SEATS") SEATS("SEATS"),
    @Json(name = "OTHER_SERVICES") OTHER_SERVICES("OTHER_SERVICES")
}
