/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Order Management
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * information related to the aircraft
 * @property code IATA aircraft code (http://www.flugzeuginfo.net/table_accodes_iata_en.php) 
 */
@JsonClass(generateAdapter = true)
data class AircraftEquipment(
    @Json(name = "code") @field:Json(name = "code") var code: String? = null
)
