/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Order Management
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
* airline remark type
* Values: OTHER_SERVICE_INFORMATION,KEYWORD,OTHER_SERVICE,CLIENT_ID
*/
@JsonClass(generateAdapter = false)
enum class AirlineRemarkType(val value: String) {
    @Json(name = "OTHER_SERVICE_INFORMATION") OTHER_SERVICE_INFORMATION("OTHER_SERVICE_INFORMATION"),
    @Json(name = "KEYWORD") KEYWORD("KEYWORD"),
    @Json(name = "OTHER_SERVICE") OTHER_SERVICE("OTHER_SERVICE"),
    @Json(name = "CLIENT_ID") CLIENT_ID("CLIENT_ID")
}
