/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Order Management
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property documentType Type of the travel document
 * @property documentNumber Identifier of the travel document prefixed by its owner code [NALC - 3 digits]. Can either be a primary or a conjunctive document number. Necessary for TicketingReference definition.
 * @property documentStatus Status of the travel document contained in the fare element
 */
@JsonClass(generateAdapter = true)
data class AirTravelDocumentCommon(
    @Json(name = "documentType") @field:Json(name = "documentType") var documentType: AirTravelDocumentCommon.DocumentTypeEnum? = null,
    @Json(name = "documentNumber") @field:Json(name = "documentNumber") var documentNumber: String? = null,
    @Json(name = "documentStatus") @field:Json(name = "documentStatus") var documentStatus: AirTravelDocumentCommon.DocumentStatusEnum? = null
) {
    /**
     * Type of the travel document
     * Values: ETICKET, PTICKET, EMD, MCO
     */
    @JsonClass(generateAdapter = false)
    enum class DocumentTypeEnum(val value: String) {
        @Json(name = "ETICKET") ETICKET("ETICKET"),
        @Json(name = "PTICKET") PTICKET("PTICKET"),
        @Json(name = "EMD") EMD("EMD"),
        @Json(name = "MCO") MCO("MCO")
    }
    /**
     * Status of the travel document contained in the fare element
     * Values: ISSUED, REFUNDED, VOID, ORIGINAL, EXCHANGED
     */
    @JsonClass(generateAdapter = false)
    enum class DocumentStatusEnum(val value: String) {
        @Json(name = "ISSUED") ISSUED("ISSUED"),
        @Json(name = "REFUNDED") REFUNDED("REFUNDED"),
        @Json(name = "VOID") VOID("VOID"),
        @Json(name = "ORIGINAL") ORIGINAL("ORIGINAL"),
        @Json(name = "EXCHANGED") EXCHANGED("EXCHANGED")
    }
}
