/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property tourName
 * @property tourReference
 */
@JsonClass(generateAdapter = true)
data class AllotmentDetails(
    @Json(name = "tourName") @field:Json(name = "tourName") var tourName: String? = null,
    @Json(name = "tourReference") @field:Json(name = "tourReference") var tourReference: String? = null
)
