/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Most Traveled Destinations
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property flights
 * @property travelers
 */
@JsonClass(generateAdapter = true)
data class Analytics(
    @Json(name = "flights") @field:Json(name = "flights") var flights: Flights? = null,
    @Json(name = "travelers") @field:Json(name = "travelers") var travelers: Travelers? = null
)
