/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * record associated to the order
 * @property reference Record locator [Amadeus or OA] with which the current reservation is related. In case of a codeshare relation, it enables to identify the operating PNR.
 * @property creationDate Creation date of the referenced reservation. Date and time in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-ddThh:mm:ss.sss format, e.g. 2019-07-09T12:30:00.000
 * @property originSystemCode Designates the system which has originated the referenced reservation.
 * @property flightOfferId id of the impacted flight offer
 */
@JsonClass(generateAdapter = true)
data class AssociatedRecord(
    @Json(name = "reference") @field:Json(name = "reference") var reference: String? = null,
    @Json(name = "creationDate") @field:Json(name = "creationDate") var creationDate: String? = null,
    @Json(name = "originSystemCode") @field:Json(name = "originSystemCode") var originSystemCode: String? = null,
    @Json(name = "flightOfferId") @field:Json(name = "flightOfferId") var flightOfferId: String? = null
)
