/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Provides information on ticketing arrangements and Amadeus Time Limits
 * @property code
 * @property queue
 * @property text Free text
 */
@JsonClass(generateAdapter = true)
data class AutomatedProcessCommon(
    @Json(name = "code") @field:Json(name = "code") var code: AutomatedProcessCode? = null,
    @Json(name = "queue") @field:Json(name = "queue") var queue: Queue? = null,
    @Json(name = "text") @field:Json(name = "text") var text: String? = null
)
