/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.ZonedDateTime

/**
 * automatic process applied to the Order
 * @property code
 * @property queue
 * @property text Free text
 * @property delay Delay before applying process in days
 * @property officeId Office into which the process must be triggered.
 * @property dateTime Datetime limit at which the process takes action in case issuance is not done.
 */
@JsonClass(generateAdapter = true)
data class AutomatedProcess(
    @Json(name = "code") @field:Json(name = "code") var code: AutomatedProcessCode? = null,
    @Json(name = "queue") @field:Json(name = "queue") var queue: Queue? = null,
    @Json(name = "text") @field:Json(name = "text") var text: String? = null,
    @Json(name = "delay") @field:Json(name = "delay") var delay: String? = null,
    @Json(name = "officeId") @field:Json(name = "officeId") var officeId: String? = null,
    @Json(name = "dateTime") @field:Json(name = "dateTime") var dateTime: ZonedDateTime? = null
)
