/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
* queuing action to be taken
* Values: IMMEDIATE,DELAYED,ERROR
*/
@JsonClass(generateAdapter = false)
enum class AutomatedProcessCode(val value: String) {
    @Json(name = "IMMEDIATE") IMMEDIATE("IMMEDIATE"),
    @Json(name = "DELAYED") DELAYED("DELAYED"),
    @Json(name = "ERROR") ERROR("ERROR")
}
