/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * b2b wallet
 * @property cardId card identifier
 * @property cardUsageName card usage name
 * @property cardFriendlyName card name
 * @property reportingData
 * @property virtualCreditCardDetails
 * @property flightOfferIds Id of the concern flightOffers
 */
@JsonClass(generateAdapter = true)
data class B2bWallet(
    @Json(name = "cardId") @field:Json(name = "cardId") var cardId: String? = null,
    @Json(name = "cardUsageName") @field:Json(name = "cardUsageName") var cardUsageName: String? = null,
    @Json(name = "cardFriendlyName") @field:Json(name = "cardFriendlyName") var cardFriendlyName: String? = null,
    @Json(name = "reportingData") @field:Json(name = "reportingData") var reportingData: List<ReportingData>? = null,
    @Json(name = "virtualCreditCardDetails") @field:Json(name = "virtualCreditCardDetails") var virtualCreditCardDetails: VirtualCreditCardDetails? = null,
    @Json(name = "flightOfferIds") @field:Json(name = "flightOfferIds") var flightOfferIds: List<String>? = null
)
