/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Seatmap Display
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * baggageAllowance
 * @property excessRate
 * @property quantity Total number of units
 * @property weight Weight of the baggage allowance
 * @property weightUnit Code to qualify unit as pounds or kilos
 */
@JsonClass(generateAdapter = true)
data class BaggageAllowance(
    @Json(name = "excessRate") @field:Json(name = "excessRate") var excessRate: ElementaryPrice? = null,
    @Json(name = "quantity") @field:Json(name = "quantity") var quantity: Int? = null,
    @Json(name = "weight") @field:Json(name = "weight") var weight: Int? = null,
    @Json(name = "weightUnit") @field:Json(name = "weightUnit") var weightUnit: String? = null
)
