/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Offers Price
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * pricing condition at booking level
 * @property invoiceAddressRequired If true, an invoice address is required for the creation of the flight-order
 * @property mailingAddressRequired If true, a postal address is required for the creation of the flight-order
 * @property emailAddressRequired If true, an email address is required for the creation of the flight-order
 * @property phoneCountryCodeRequired If true, the phone country code (e.g. &#39;33&#39;) associated for each phone number is required for the creation of the flight-order
 * @property mobilePhoneNumberRequired If true, a mobile phone number is required for the creation of the flight-order
 * @property phoneNumberRequired If true, a phone number is required for the creation of the flight-order
 * @property postalCodeRequired If true, a postal code is required for the creation of the flight-order
 * @property travelerRequirements traveler pricing condition
 */
@JsonClass(generateAdapter = true)
data class BookingRequirements(
    @Json(name = "invoiceAddressRequired") @field:Json(name = "invoiceAddressRequired") var invoiceAddressRequired: Boolean? = null,
    @Json(name = "mailingAddressRequired") @field:Json(name = "mailingAddressRequired") var mailingAddressRequired: Boolean? = null,
    @Json(name = "emailAddressRequired") @field:Json(name = "emailAddressRequired") var emailAddressRequired: Boolean? = null,
    @Json(name = "phoneCountryCodeRequired") @field:Json(name = "phoneCountryCodeRequired") var phoneCountryCodeRequired: Boolean? = null,
    @Json(name = "mobilePhoneNumberRequired") @field:Json(name = "mobilePhoneNumberRequired") var mobilePhoneNumberRequired: Boolean? = null,
    @Json(name = "phoneNumberRequired") @field:Json(name = "phoneNumberRequired") var phoneNumberRequired: Boolean? = null,
    @Json(name = "postalCodeRequired") @field:Json(name = "postalCodeRequired") var postalCodeRequired: Boolean? = null,
    @Json(name = "travelerRequirements") @field:Json(name = "travelerRequirements") var travelerRequirements: List<PassengerConditions>? = null
)
