/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Offers Search
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Restriction towards carriers.
 * @property blacklistedInEUAllowed This flag enable/disable filtering of blacklisted airline by EU. The list of the banned airlines is published in the Official Journal of the European Union, where they are included as annexes A and B to the Commission Regulation. The blacklist of an airline can concern all its flights or some specific aircraft types pertaining to the airline
 * @property excludedCarrierCodes This option ensures that the system will only consider these airlines.
 * @property includedCarrierCodes This option ensures that the system will only consider these airlines.
 */
@JsonClass(generateAdapter = true)
data class CarrierRestrictions(
    @Json(name = "blacklistedInEUAllowed") @field:Json(name = "blacklistedInEUAllowed") var blacklistedInEUAllowed: Boolean? = null,
    @Json(name = "excludedCarrierCodes") @field:Json(name = "excludedCarrierCodes") var excludedCarrierCodes: List<String>? = null,
    @Json(name = "includedCarrierCodes") @field:Json(name = "includedCarrierCodes") var includedCarrierCodes: List<String>? = null
)
