/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Order Management
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property weight Weight of Co2 emitted for the concerned segment
 * @property weightUnit Code to qualify unit as pounds or kilos
 * @property cabin
 */
@JsonClass(generateAdapter = true)
data class Co2Emission(
    @Json(name = "weight") @field:Json(name = "weight") var weight: Int? = null,
    @Json(name = "weightUnit") @field:Json(name = "weightUnit") var weightUnit: String? = null,
    @Json(name = "cabin") @field:Json(name = "cabin") var cabin: TravelClass? = null
)
