/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Offers Search
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.math.BigDecimal

/**
 * Restriction towards number of connections.
 * @property maxNumberOfConnections The maximal number of connections for each itinerary. Value can be 0, 1 or 2.
 * @property airportChangeAllowed Allow to change airport during connection
 * @property technicalStopsAllowed This option allows the single segment to have one or more intermediate stops (technical stops).
 */
@JsonClass(generateAdapter = true)
data class ConnectionRestriction(
    @Json(name = "maxNumberOfConnections") @field:Json(name = "maxNumberOfConnections") var maxNumberOfConnections: BigDecimal? = null,
    @Json(name = "airportChangeAllowed") @field:Json(name = "airportChangeAllowed") var airportChangeAllowed: Boolean? = null,
    @Json(name = "technicalStopsAllowed") @field:Json(name = "technicalStopsAllowed") var technicalStopsAllowed: Boolean? = null
)
