/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Order Management
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * contact information
 * @property addresseeName the name of the person addressed by these contact details
 * @property address
 * @property purpose
 * @property phones Phone numbers
 * @property companyName Name of the company
 * @property emailAddress Email address (e.g. john@smith.com)
 */
@JsonClass(generateAdapter = true)
data class Contact(
    @Json(name = "addresseeName") @field:Json(name = "addresseeName") var addresseeName: Name? = null,
    @Json(name = "address") @field:Json(name = "address") var address: Address? = null,
    @Json(name = "purpose") @field:Json(name = "purpose") var purpose: ContactPurpose? = null,
    @Json(name = "phones") @field:Json(name = "phones") var phones: List<Phone>? = null,
    @Json(name = "companyName") @field:Json(name = "companyName") var companyName: String? = null,
    @Json(name = "emailAddress") @field:Json(name = "emailAddress") var emailAddress: String? = null
)
