/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * represents a contact
 * @property addresseeName the name of the person addressed by these contact details
 * @property address
 * @property purpose
 */
@JsonClass(generateAdapter = true)
data class ContactDictionary(
    @Json(name = "addresseeName") @field:Json(name = "addresseeName") var addresseeName: Name? = null,
    @Json(name = "address") @field:Json(name = "address") var address: Address? = null,
    @Json(name = "purpose") @field:Json(name = "purpose") var purpose: ContactPurpose? = null
)
