/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Offers Search
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
* part of the trip covered by the travel class restriction (ALL_SEGMENTS if ommited)
* Values: MOST_SEGMENTS,AT_LEAST_ONE_SEGMENT,ALL_SEGMENTS
*/
@JsonClass(generateAdapter = false)
enum class Coverage(val value: String) {
    @Json(name = "MOST_SEGMENTS") MOST_SEGMENTS("MOST_SEGMENTS"),
    @Json(name = "AT_LEAST_ONE_SEGMENT") AT_LEAST_ONE_SEGMENT("AT_LEAST_ONE_SEGMENT"),
    @Json(name = "ALL_SEGMENTS") ALL_SEGMENTS("ALL_SEGMENTS")
}
