/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Offers Price
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property brand
 * @property amount
 * @property currency
 * @property flightOfferId Id of the flightOffer concerned by the credit card fee
 */
@JsonClass(generateAdapter = true)
data class CreditCardFee(
    @Json(name = "brand") @field:Json(name = "brand") var brand: PaymentBrand? = null,
    @Json(name = "amount") @field:Json(name = "amount") var amount: String? = null,
    @Json(name = "currency") @field:Json(name = "currency") var currency: String? = null,
    @Json(name = "flightOfferId") @field:Json(name = "flightOfferId") var flightOfferId: String? = null
)
