/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Seatmap Display
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * deck information
 * @property deckType A deck is a level on an aircraft. The deck location of the cabin (current possible values are upper or main) The main deck, where passengers are seated on a passenger flight. Upper deck is above the main deck where more passengers are seated.
 * @property deckConfiguration
 * @property facilities
 * @property seats
 */
@JsonClass(generateAdapter = true)
data class Deck(
    @Json(name = "deckType") @field:Json(name = "deckType") var deckType: Deck.DeckTypeEnum? = null,
    @Json(name = "deckConfiguration") @field:Json(name = "deckConfiguration") var deckConfiguration: DeckConfiguration? = null,
    @Json(name = "facilities") @field:Json(name = "facilities") var facilities: List<Facility>? = null,
    @Json(name = "seats") @field:Json(name = "seats") var seats: List<Seat>? = null
) {
    /**
     * A deck is a level on an aircraft. The deck location of the cabin (current possible values are upper or main) The main deck, where passengers are seated on a passenger flight. Upper deck is above the main deck where more passengers are seated.
     * Values: UPPER, MAIN, LOWER
     */
    @JsonClass(generateAdapter = false)
    enum class DeckTypeEnum(val value: String) {
        @Json(name = "UPPER") UPPER("UPPER"),
        @Json(name = "MAIN") MAIN("MAIN"),
        @Json(name = "LOWER") LOWER("LOWER")
    }
}
