/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Seatmap Display
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * deck dimensions are used as a reference to display the entire aircraft or to the section associated to the requested cabin (or set of cabins)
 * @property width Width (y-axis) of the deck.
 * @property length Length (x-axis) of the deck.
 * @property startSeatRow seat row where the deck is starting
 * @property endSeatRow seat row where the deck is ending
 * @property startWingsX Start x coordinate of the wings.The wings display starts relatively to the length.
 * @property endWingsX End x coordinate of the wings.The wings display ends relatively to the length.
 * @property startWingsRow seat row where the wing is starting
 * @property endWingsRow seat row where the wing is ending
 * @property exitRowsX X coordinate of the exit rows.The exit rows are displayed relatively to the length.
 */
@JsonClass(generateAdapter = true)
data class DeckConfiguration(
    @Json(name = "width") @field:Json(name = "width") var width: Int? = null,
    @Json(name = "length") @field:Json(name = "length") var length: Int? = null,
    @Json(name = "startSeatRow") @field:Json(name = "startSeatRow") var startSeatRow: Int? = null,
    @Json(name = "endSeatRow") @field:Json(name = "endSeatRow") var endSeatRow: Int? = null,
    @Json(name = "startWingsX") @field:Json(name = "startWingsX") var startWingsX: Int? = null,
    @Json(name = "endWingsX") @field:Json(name = "endWingsX") var endWingsX: Int? = null,
    @Json(name = "startWingsRow") @field:Json(name = "startWingsRow") var startWingsRow: Int? = null,
    @Json(name = "endWingsRow") @field:Json(name = "endWingsRow") var endWingsRow: Int? = null,
    @Json(name = "exitRowsX") @field:Json(name = "exitRowsX") var exitRowsX: List<Int>? = null
)
