/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Inspiration Search
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * the query parameters for which default values were used are returned here
 * @property departureDate the date, or range of dates, on which the flight will depart from the origin. Dates are specified in the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-DD format, e.g. 2017-12-25. Ranges are specified with a comma and are inclusive
 * @property oneWay if this parameter is set to true, only one-way flights are considered. If this parameter is not set or set to false, only round-trip flights are considered
 * @property duration exact duration or range of durations of the travel, in days. This parameter must not be set if oneWay is true. Ranges are specified with a comma and are inclusive, e.g. 2,8
 * @property nonStop if this parameter is set to true, only flights going from the origin to the destination with no stop in-between are considered
 * @property viewBy view the flight destinations by COUNTRY, DATE, DESTINATION, DURATION, or WEEK. View by COUNTRY to get the cheapest flight dates for every country in the given range. View by DATE to get the cheapest flight dates for every departure date in the given range. View by DURATION to get the cheapest flight dates for every departure date and for every duration in the given ranges. View by WEEK to get the cheapest flight destination for every week in the given range of departure dates
 */
@JsonClass(generateAdapter = true)
data class Defaults(
    @Json(name = "departureDate") @field:Json(name = "departureDate") var departureDate: String? = null,
    @Json(name = "oneWay") @field:Json(name = "oneWay") var oneWay: Boolean? = null,
    @Json(name = "duration") @field:Json(name = "duration") var duration: String? = null,
    @Json(name = "nonStop") @field:Json(name = "nonStop") var nonStop: Boolean? = null,
    @Json(name = "viewBy") @field:Json(name = "viewBy") var viewBy: Defaults.ViewByEnum? = null
) {
    /**
     * view the flight destinations by COUNTRY, DATE, DESTINATION, DURATION, or WEEK. View by COUNTRY to get the cheapest flight dates for every country in the given range. View by DATE to get the cheapest flight dates for every departure date in the given range. View by DURATION to get the cheapest flight dates for every departure date and for every duration in the given ranges. View by WEEK to get the cheapest flight destination for every week in the given range of departure dates
     * Values: COUNTRY, DATE, DESTINATION, DURATION, WEEK
     */
    @JsonClass(generateAdapter = false)
    enum class ViewByEnum(val value: String) {
        @Json(name = "COUNTRY") COUNTRY("COUNTRY"),
        @Json(name = "DATE") DATE("DATE"),
        @Json(name = "DURATION") DURATION("DURATION"),
        @Json(name = "WEEK") WEEK("WEEK")
    }
}
