/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Delay Prediction
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property type the resource name (&#x60;prediction&#x60;)
 * @property subType
 * @property id item identifier
 * @property result
 * @property probability probability of the forecast (between 0 and 1)
 */
@JsonClass(generateAdapter = true)
data class DelayPrediction(
    @Json(name = "type") @field:Json(name = "type") var type: String? = null,
    @Json(name = "subType") @field:Json(name = "subType") var subType: String? = null,
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "result") @field:Json(name = "result") var result: DelayPrediction.PredictionResultType? = null,
    @Json(name = "probability") @field:Json(name = "probability") var probability: String? = null
) {

    /**
     * forecast description
     * Values: LESS_THAN_30_MINUTES,BETWEEN_30_AND_60_MINUTES,BETWEEN_60_AND_120_MINUTES,OVER_120_MINUTES_OR_CANCELLED
     */
    @JsonClass(generateAdapter = false)
    enum class PredictionResultType(val value: String) {
        @Json(name = "LESS_THAN_30_MINUTES") LESS_THAN_30_MINUTES("LESS_THAN_30_MINUTES"),
        @Json(name = "BETWEEN_30_AND_60_MINUTES") BETWEEN_30_AND_60_MINUTES("BETWEEN_30_AND_60_MINUTES"),
        @Json(name = "BETWEEN_60_AND_120_MINUTES") BETWEEN_60_AND_120_MINUTES("BETWEEN_60_AND_120_MINUTES"),
        @Json(name = "OVER_120_MINUTES_OR_CANCELLED") OVER_120_MINUTES_OR_CANCELLED("OVER_120_MINUTES_OR_CANCELLED")
    }
}
