/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Order Management
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property descriptionType
 * @property text
 */
@JsonClass(generateAdapter = true)
data class Description(
    @Json(name = "descriptionType") @field:Json(name = "descriptionType") var descriptionType: String? = null,
    @Json(name = "text") @field:Json(name = "text") var text: String? = null
)
