/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Seatmap Display
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property locations
 * @property aircraft
 * @property currencies
 * @property carriers
 * @property facilities
 * @property seatCharacteristics
 */
@JsonClass(generateAdapter = true)
data class Dictionaries(
    @Json(name = "locations") @field:Json(name = "locations") var locations: LocationEntry? = null,
    @Json(name = "aircraft") @field:Json(name = "aircraft") var aircraft: AircraftEntry? = null,
    @Json(name = "currencies") @field:Json(name = "currencies") var currencies: CurrencyEntry? = null,
    @Json(name = "carriers") @field:Json(name = "carriers") var carriers: CarrierEntry? = null,
    @Json(name = "facilities") @field:Json(name = "facilities") var facilities: FacilityDictionary? = null,
    @Json(name = "seatCharacteristics") @field:Json(name = "seatCharacteristics") var seatCharacteristics: SeatCharacteristicDictionary? = null
)
