/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Choice Prediction
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models


typealias DictionaryEntry = Map<String, String>


