/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * traveler discount
 * @property subType
 * @property cityName city of residence
 * @property travelerType
 * @property cardNumber resident card number
 * @property certificateNumber resident certificate number
 */
@JsonClass(generateAdapter = true)
data class Discount(
    @Json(name = "subType") @field:Json(name = "subType") var subType: DiscountType? = null,
    @Json(name = "cityName") @field:Json(name = "cityName") var cityName: String? = null,
    @Json(name = "travelerType") @field:Json(name = "travelerType") var travelerType: DiscountTravelerType? = null,
    @Json(name = "cardNumber") @field:Json(name = "cardNumber") var cardNumber: String? = null,
    @Json(name = "certificateNumber") @field:Json(name = "certificateNumber") var certificateNumber: String? = null
)
