/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
* type of discount applied
* Values: SPANISH_RESIDENT,AIR_FRANCE_DOMESTIC,AIR_FRANCE_COMBINED,AIR_FRANCE_METROPOLITAN
*/
@JsonClass(generateAdapter = false)
enum class DiscountType(val value: String) {
    @Json(name = "SPANISH_RESIDENT") SPANISH_RESIDENT("SPANISH_RESIDENT"),
    @Json(name = "AIR_FRANCE_DOMESTIC") AIR_FRANCE_DOMESTIC("AIR_FRANCE_DOMESTIC"),
    @Json(name = "AIR_FRANCE_COMBINED") AIR_FRANCE_COMBINED("AIR_FRANCE_COMBINED"),
    @Json(name = "AIR_FRANCE_METROPOLITAN") AIR_FRANCE_METROPOLITAN("AIR_FRANCE_METROPOLITAN")
}
