/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
* type of discount applied
* Values: SPANISH_CITIZEN,EUROPEAN_CITIZEN,GOVERNMENT_WORKER,MILITARY,MINOR_WITHOUT_ID
*/
@JsonClass(generateAdapter = false)
enum class DiscountTravelerType(val value: String) {
    @Json(name = "SPANISH_CITIZEN") SPANISH_CITIZEN("SPANISH_CITIZEN"),
    @Json(name = "EUROPEAN_CITIZEN") EUROPEAN_CITIZEN("EUROPEAN_CITIZEN"),
    @Json(name = "GOVERNMENT_WORKER") GOVERNMENT_WORKER("GOVERNMENT_WORKER"),
    @Json(name = "MILITARY") MILITARY("MILITARY"),
    @Json(name = "MINOR_WITHOUT_ID") MINOR_WITHOUT_ID("MINOR_WITHOUT_ID")
}
