/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Airport Nearest Relevant
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property value great-circle distance between two locations. This distance thus do not take into account traffic conditions; international boundaries; mountains; water; or other elements that might make the a nearby location hard to reach.
 * @property unit unit of the distance
 */
@JsonClass(generateAdapter = true)
data class Distance(
    @Json(name = "value") @field:Json(name = "value") var value: Int? = null,
    @Json(name = "unit") @field:Json(name = "unit") var unit: Distance.UnitEnum? = null
) {
    /**
     * unit of the distance
     * Values: KM
     */
    @JsonClass(generateAdapter = false)
    enum class UnitEnum(val value: String) {
        @Json(name = "KM")
        KM("KM")
    }
}
