/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
* the nature/type of the document
* Values: VISA,PASSPORT,IDENTITY_CARD,KNOWN_TRAVELER,REDRESS
*/
@JsonClass(generateAdapter = false)
enum class DocumentType(val value: String) {
    @Json(name = "VISA") VISA("VISA"),
    @Json(name = "PASSPORT") PASSPORT("PASSPORT"),
    @Json(name = "IDENTITY_CARD") IDENTITY_CARD("IDENTITY_CARD"),
    @Json(name = "KNOWN_TRAVELER") KNOWN_TRAVELER("KNOWN_TRAVELER"),
    @Json(name = "REDRESS") REDRESS("REDRESS")
}
