/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * elementaryPrice
 * @property amount Amount of the fare. could be alpha numeric. Ex- 500.20 or 514.13A, &#39;A&#39;signifies additional collection.
 * @property currencyCode Currency type of the fare.
 */
@JsonClass(generateAdapter = true)
data class ElementaryPrice(
    @Json(name = "amount") @field:Json(name = "amount") var amount: String? = null,
    @Json(name = "currencyCode") @field:Json(name = "currencyCode") var currencyCode: String? = null
)
