/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * emergency contact number
 * @property addresseeName Adressee name (e.g. in case of emergency purpose it corresponds to name of the person to be contacted).
 * @property countryCode Country code of the country (ISO3166-1). E.g. \&quot;US\&quot; for the United States
 * @property number Phone number. Composed of digits only. The number of digits depends on the country.
 * @property text additional details
 */
@JsonClass(generateAdapter = true)
data class EmergencyContact(
    @Json(name = "addresseeName") @field:Json(name = "addresseeName") var addresseeName: String? = null,
    @Json(name = "countryCode") @field:Json(name = "countryCode") var countryCode: String? = null,
    @Json(name = "number") @field:Json(name = "number") var number: String? = null,
    @Json(name = "text") @field:Json(name = "text") var text: String? = null
)
