/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Seatmap Display
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

/**
 * on board facilities map. E.g: bulkhead, closet, exit door, galley, lavatory
 */
typealias FacilityDictionary = Map<String, String>


