/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Fare details of the segment
 * @property segmentId Id of the segment
 * @property cabin
 * @property fareBasis Fare basis specifying the rules of a fare. Usually, though not always, is composed of the booking class code followed by a set of letters and digits representing other characteristics of the ticket, such as refundability, minimum stay requirements, discounts or special promotional elements.
 * @property brandedFare The name of the Fare Family corresponding to the fares. Only for the GDS provider and if the airline has fare families filled
 * @property `class` The code of the booking class, a.k.a. class of service or Reservations/Booking Designator (RBD)
 * @property isAllotment True if the corresponding booking class is in an allotment
 * @property allotmentDetails
 * @property sliceDiceIndicator
 * @property includedCheckedBags Details of the included checked bags
 * @property additionalServices
 */
@JsonClass(generateAdapter = true)
data class FareDetailsBySegment(
    @Json(name = "segmentId") @field:Json(name = "segmentId") var segmentId: String,
    @Json(name = "cabin") @field:Json(name = "cabin") var cabin: TravelClass? = null,
    @Json(name = "fareBasis") @field:Json(name = "fareBasis") var fareBasis: String? = null,
    @Json(name = "brandedFare") @field:Json(name = "brandedFare") var brandedFare: String? = null,
    @Json(name = "class") @field:Json(name = "class") var `class`: String? = null,
    @Json(name = "isAllotment") @field:Json(name = "isAllotment") var isAllotment: Boolean? = null,
    @Json(name = "allotmentDetails") @field:Json(name = "allotmentDetails") var allotmentDetails: AllotmentDetails? = null,
    @Json(name = "sliceDiceIndicator") @field:Json(name = "sliceDiceIndicator") var sliceDiceIndicator: SliceDiceIndicator? = null,
    @Json(name = "includedCheckedBags") @field:Json(name = "includedCheckedBags") var includedCheckedBags: BaggageAllowance? = null,
    @Json(name = "additionalServices") @field:Json(name = "additionalServices") var additionalServices: AdditionalServicesRequest? = null
)
