/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
* type of fee
* Values: TICKETING,FORM_OF_PAYMENT,SUPPLIER
*/
@JsonClass(generateAdapter = false)
enum class FeeType(val value: String) {
    @Json(name = "TICKETING") TICKETING("TICKETING"),
    @Json(name = "FORM_OF_PAYMENT") FORM_OF_PAYMENT("FORM_OF_PAYMENT"),
    @Json(name = "SUPPLIER") SUPPLIER("SUPPLIER")
}
