/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Cheapest Date Search
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property type the resource name
 * @property origin
 * @property destination
 * @property departureDate
 * @property returnDate
 * @property price
 * @property links
 */
@JsonClass(generateAdapter = true)
data class FlightDate(
    @Json(name = "type") @field:Json(name = "type") var type: String? = null,
    @Json(name = "origin") @field:Json(name = "origin") var origin: String? = null,
    @Json(name = "destination") @field:Json(name = "destination") var destination: String? = null,
    @Json(name = "departureDate") @field:Json(name = "departureDate") var departureDate: String? = null,
    @Json(name = "returnDate") @field:Json(name = "returnDate") var returnDate: String? = null,
    @Json(name = "price") @field:Json(name = "price") var price: Price? = null,
    @Json(name = "links") @field:Json(name = "links") var links: FlightDateLinks? = null
)
