/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Seatmap Display
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property `data`
 * @property included
 */
@JsonClass(generateAdapter = true)
data class FlightOffers(
    @Json(name = "data") @field:Json(name = "data") var `data`: List<FlightMinusoffer>,
    @Json(name = "included") @field:Json(name = "included") var included: TravelersMap? = null
)
