/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Choice Prediction
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 * @property type the resource name
 * @property id the resource identifier
 * @property choiceProbability the choice probability of this Flight Offer
 * @property offerItems
 */
@JsonClass(generateAdapter = true)
data class FlightOffer(
    @Json(name = "type") @field:Json(name = "type") var type: String? = null,
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "choiceProbability") @field:Json(name = "choiceProbability") var choiceProbability: String? = null,
    @Json(name = "offerItems") @field:Json(name = "offerItems") var offerItems: List<OfferItem>? = null
)

