/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Offers Price
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * input parameter to price flight offers element
 * @property type the resource name
 * @property flightOffers list of flight offer to price
 * @property payments payment information for retrieve eventual credit card fees
 * @property travelers list of travelers
 */
@JsonClass(generateAdapter = true)
data class FlightOfferPricingInput(
    @Json(name = "type") @field:Json(name = "type") var type: String,
    @Json(name = "flightOffers") @field:Json(name = "flightOffers") var flightOffers: List<FlightMinusoffer>,
    @Json(name = "payments") @field:Json(name = "payments") var payments: List<Payment>? = null,
    @Json(name = "travelers") @field:Json(name = "travelers") var travelers: List<TravelerElement>? = null
)
