/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Offers Price
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * priced flight Offers and conditions
 * @property type the resource name
 * @property flightOffers list of flight offer to price
 * @property bookingRequirements
 */
@JsonClass(generateAdapter = true)
data class FlightOfferPricingOutput(
    @Json(name = "type") @field:Json(name = "type") var type: String,
    @Json(name = "flightOffers") @field:Json(name = "flightOffers") var flightOffers: List<FlightMinusoffer>,
    @Json(name = "bookingRequirements") @field:Json(name = "bookingRequirements") var bookingRequirements: BookingRequirements? = null
)
