/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Offers Search
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.math.BigDecimal

/**
 * @property crossBorderAllowed Allows to search a location outside the borders when a radius around a location is specified. Default is false.
 * @property moreOvernightsAllowed This flag enables/disables the possibility to have more overnight flights in Low Fare Search
 * @property returnToDepartureAirport This option force to retrieve flight-offer with a departure and a return in the same airport
 * @property railSegmentAllowed This flag enable/disable filtering of rail segment (TGV AIR, RAIL ...)
 * @property busSegmentAllowed This flag enable/disable filtering of bus segment
 * @property maxFlightTime This option allows to modify the value for the Elapsed Flying Time (EFT) masterPricer option
 * @property carrierRestrictions
 * @property cabinRestrictions Restriction towards cabins.
 * @property connectionRestriction
 */
@JsonClass(generateAdapter = true)
data class FlightFilters(
    @Json(name = "crossBorderAllowed") @field:Json(name = "crossBorderAllowed") var crossBorderAllowed: Boolean? = null,
    @Json(name = "moreOvernightsAllowed") @field:Json(name = "moreOvernightsAllowed") var moreOvernightsAllowed: Boolean? = null,
    @Json(name = "returnToDepartureAirport") @field:Json(name = "returnToDepartureAirport") var returnToDepartureAirport: Boolean? = null,
    @Json(name = "railSegmentAllowed") @field:Json(name = "railSegmentAllowed") var railSegmentAllowed: Boolean? = null,
    @Json(name = "busSegmentAllowed") @field:Json(name = "busSegmentAllowed") var busSegmentAllowed: Boolean? = null,
    @Json(name = "maxFlightTime") @field:Json(name = "maxFlightTime") var maxFlightTime: BigDecimal? = null,
    @Json(name = "carrierRestrictions") @field:Json(name = "carrierRestrictions") var carrierRestrictions: CarrierRestrictions? = null,
    @Json(name = "cabinRestrictions") @field:Json(name = "cabinRestrictions") var cabinRestrictions: List<CabinRestriction>? = null,
    @Json(name = "connectionRestriction") @field:Json(name = "connectionRestriction") var connectionRestriction: ConnectionRestriction? = null
)
