/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Offers Price
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.ZonedDateTime

/**
 * details of stops for direct or change of gauge flights
 * @property iataCode [IATA airline codes](http://www.iata.org/publications/Pages/code-search.aspx)
 * @property newAircraft
 * @property duration stop duration in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) PnYnMnDTnHnMnS format, e.g. PT2H10M
 * @property arrivalAt arrival at the stop in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-ddThh:mm±hh:mm format, e.g. 2017-02-10T20:40:00+02:00
 * @property departureAt departure from the stop in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-ddThh:mm±hh:mm format, e.g. 2017-02-10T20:40:00+02:00
 */
@JsonClass(generateAdapter = true)
data class FlightStop(
    @Json(name = "iataCode") @field:Json(name = "iataCode") var iataCode: String? = null,
    @Json(name = "newAircraft") @field:Json(name = "newAircraft") var newAircraft: AircraftEquipment? = null,
    @Json(name = "duration") @field:Json(name = "duration") var duration: String? = null,
    @Json(name = "arrivalAt") @field:Json(name = "arrivalAt") var arrivalAt: ZonedDateTime? = null,
    @Json(name = "departureAt") @field:Json(name = "departureAt") var departureAt: ZonedDateTime? = null
)
