/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Inspiration Search
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property flightDates
 * @property flightOffers
 */
@JsonClass(generateAdapter = true)
data class FlightDestinationLinks(
    @Json(name = "flightDates") @field:Json(name = "flightDates") var flightDates: String? = null,
    @Json(name = "flightOffers") @field:Json(name = "flightOffers") var flightOffers: String? = null
)
