/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Cheapest Date Search
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property flightDestinations
 * @property flightOffers
 */
@JsonClass(generateAdapter = true)
data class FlightDateLinks(
    @Json(name = "flightDestinations") @field:Json(name = "flightDestinations") var flightDestinations: String? = null,
    @Json(name = "flightOffers") @field:Json(name = "flightOffers") var flightOffers: String? = null
)
