/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Order Management
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.math.BigDecimal

/**
 * @property type the resource name
 * @property id Id of the flight offer
 * @property source
 * @property instantTicketingRequired If true, inform that a ticketing will be required at booking step.
 * @property disablePricing BOOK step ONLY - If true, allows to book a PNR without pricing. Only for the source \&quot;GDS\&quot;
 * @property nonHomogeneous If true, upon completion of the booking, this pricing solution is expected to yield multiple records (a record contains booking information confirmed and stored, typically a Passenger Name Record (PNR), in the provider GDS or system)
 * @property oneWay If true, the flight offer fulfills only one originDestination and has to be combined with other oneWays to complete the whole journey.
 * @property paymentCardRequired If true, a payment card is mandatory to book this flight offer
 * @property lastTicketingDate If booked on the same day as the search (with respect to timezone), this flight offer is guaranteed to be thereafter valid for ticketing until this date (included). Unspecified when it does not make sense for this flight offer (e.g. no control over ticketing once booked). YYYY-MM-DD format, e.g. 2019-06-07
 * @property numberOfBookableSeats Number of seats bookable in a single request. Can not be higher than 9.
 * @property itineraries
 * @property price
 * @property pricingOptions
 * @property validatingAirlineCodes This option ensures that the system will only consider these airlines.
 * @property travelerPricings Fare information for each traveler/segment
 * @property fareRules Fare rules of the flight offer
 */
@JsonClass(generateAdapter = true)
data class FlightMinusoffer(
    @Json(name = "type") @field:Json(name = "type") var type: String,
    @Json(name = "id") @field:Json(name = "id") var id: String,
    @Json(name = "source") @field:Json(name = "source") var source: FlightOfferSource,
    @Json(name = "instantTicketingRequired") @field:Json(name = "instantTicketingRequired") var instantTicketingRequired: Boolean? = null,
    @Json(name = "disablePricing") @field:Json(name = "disablePricing") var disablePricing: Boolean? = null,
    @Json(name = "nonHomogeneous") @field:Json(name = "nonHomogeneous") var nonHomogeneous: Boolean? = null,
    @Json(name = "oneWay") @field:Json(name = "oneWay") var oneWay: Boolean? = null,
    @Json(name = "paymentCardRequired") @field:Json(name = "paymentCardRequired") var paymentCardRequired: Boolean? = null,
    @Json(name = "lastTicketingDate") @field:Json(name = "lastTicketingDate") var lastTicketingDate: String? = null,
    @Json(name = "numberOfBookableSeats") @field:Json(name = "numberOfBookableSeats") var numberOfBookableSeats: BigDecimal? = null,
    @Json(name = "itineraries") @field:Json(name = "itineraries") var itineraries: List<Itineraries>? = null,
    @Json(name = "price") @field:Json(name = "price") var price: Price? = null,
    @Json(name = "pricingOptions") @field:Json(name = "pricingOptions") var pricingOptions: PricingOptions? = null,
    @Json(name = "validatingAirlineCodes") @field:Json(name = "validatingAirlineCodes") var validatingAirlineCodes: List<String>? = null,
    @Json(name = "travelerPricings") @field:Json(name = "travelerPricings") var travelerPricings: List<TravelerPricing>? = null,
    @Json(name = "fareRules") @field:Json(name = "fareRules") var fareRules: FareRules? = null
)
