/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Offers Price
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * defining a flight segment; including both operating and marketing details when applicable
 * @property departure
 * @property arrival
 * @property carrierCode providing the airline / carrier code
 * @property number the flight number as assigned by the carrier
 * @property suffix the flight number suffix as assigned by the carrier
 * @property aircraft
 * @property `class` reservation booking designator (RBD) of the carrier
 * @property cabin booking cabin / class of service of the carrier
 * @property operating
 * @property duration stop duration in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) PnYnMnDTnHnMnS format, e.g. PT2H10M
 * @property stops information regarding the different stops composing the flight segment. E.g. technical stop, change of gauge...
 */
@JsonClass(generateAdapter = true)
data class FlightSegment(
    @Json(name = "departure") @field:Json(name = "departure") var departure: FlightEndPoint? = null,
    @Json(name = "arrival") @field:Json(name = "arrival") var arrival: FlightEndPoint? = null,
    @Json(name = "carrierCode") @field:Json(name = "carrierCode") var carrierCode: String? = null,
    @Json(name = "number") @field:Json(name = "number") var number: String? = null,
    @Json(name = "suffix") @field:Json(name = "suffix") var suffix: String? = null,
    @Json(name = "aircraft") @field:Json(name = "aircraft") var aircraft: AircraftEquipment? = null,
    @Json(name = "class") @field:Json(name = "class") var `class`: String? = null,
    @Json(name = "cabin") @field:Json(name = "cabin") var cabin: String? = null,
    @Json(name = "operating") @field:Json(name = "operating") var operating: OperatingFlight? = null,
    @Json(name = "duration") @field:Json(name = "duration") var duration: String? = null,
    @Json(name = "stops") @field:Json(name = "stops") var stops: List<FlightStop>? = null
)
