/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
* source of the flight offer
* Values: GDS,PYTON
*/
@JsonClass(generateAdapter = false)
enum class FlightOfferSource(val value: String) {
    @Json(name = "GDS") GDS("GDS"),
    @Json(name = "PYTON") PYTON("PYTON")
}
