/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Offers Price
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.ZonedDateTime

/**
 * departure or arrival information
 * @property iataCode [IATA airline codes](http://www.iata.org/publications/Pages/code-search.aspx)
 * @property terminal terminal name / number
 * @property gate gate information
 * @property at local date and time in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-ddThh:mm±hh:mm format, e.g. 2017-02-10T20:40:00+02:00
 */
@JsonClass(generateAdapter = true)
data class FlightEndPoint(
    @Json(name = "iataCode") @field:Json(name = "iataCode") var iataCode: String? = null,
    @Json(name = "terminal") @field:Json(name = "terminal") var terminal: String? = null,
    @Json(name = "gate") @field:Json(name = "gate") var gate: String? = null,
    @Json(name = "at") @field:Json(name = "at") var at: ZonedDateTime? = null
)
