/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Order Management
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * input parameter to create a flight order
 * @property type the resource name
 * @property id unique identifier of the flight order
 * @property queuingOfficeId office Id where to queue the order
 * @property ownerOfficeId office Id where will be transfered the ownership of the order
 * @property associatedRecords list of associated record
 * @property flightOffers list of flight offer
 * @property travelers list of travelers
 * @property remarks list of global remarks
 * @property formOfPayments list of form of payments
 * @property ticketingAgreement
 * @property automatedProcess list of automatic queuing
 * @property contacts list of general contact information
 * @property tickets list of tickets
 */
@JsonClass(generateAdapter = true)
data class FlightOrderCreateQuery(
    @Json(name = "type") @field:Json(name = "type") var type: String,
    @Json(name = "flightOffers") @field:Json(name = "flightOffers") var flightOffers: List<FlightMinusoffer>,
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "queuingOfficeId") @field:Json(name = "queuingOfficeId") var queuingOfficeId: String? = null,
    @Json(name = "ownerOfficeId") @field:Json(name = "ownerOfficeId") var ownerOfficeId: String? = null,
    @Json(name = "associatedRecords") @field:Json(name = "associatedRecords") var associatedRecords: List<AssociatedRecord>? = null,
    @Json(name = "travelers") @field:Json(name = "travelers") var travelers: List<TravelerElement>? = null,
    @Json(name = "remarks") @field:Json(name = "remarks") var remarks: Remarks? = null,
    @Json(name = "formOfPayments") @field:Json(name = "formOfPayments") var formOfPayments: List<FormOfPayment>? = null,
    @Json(name = "ticketingAgreement") @field:Json(name = "ticketingAgreement") var ticketingAgreement: TicketingAgreement? = null,
    @Json(name = "automatedProcess") @field:Json(name = "automatedProcess") var automatedProcess: List<AutomatedProcess>? = null,
    @Json(name = "contacts") @field:Json(name = "contacts") var contacts: List<Contact>? = null,
    @Json(name = "tickets") @field:Json(name = "tickets") var tickets: List<AirTravelDocument>? = null
)
