/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * form of payment used
 * @property b2bWallet payment with the solution B2B Wallet
 * @property creditCard payment with a credit card
 * @property other payment with an other method
 */
@JsonClass(generateAdapter = true)
data class FormOfPayment(
    @Json(name = "b2bWallet") @field:Json(name = "b2bWallet") var b2bWallet: B2bWallet? = null,
    @Json(name = "creditCard") @field:Json(name = "creditCard") var creditCard: CreditCard? = null,
    @Json(name = "other") @field:Json(name = "other") var other: CreditCard? = null
)
