/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property subType
 * @property category remark category
 * @property text remark free text
 * @property travelerIds Id of the concerned traveler
 * @property flightOfferIds Id of the concern flightOffers
 */
@JsonClass(generateAdapter = true)
data class GeneralRemark(
    @Json(name = "subType") @field:Json(name = "subType") var subType: GeneralRemarkType,
    @Json(name = "text") @field:Json(name = "text") var text: String,
    @Json(name = "category") @field:Json(name = "category") var category: String? = null,
    @Json(name = "travelerIds") @field:Json(name = "travelerIds") var travelerIds: List<String>? = null,
    @Json(name = "flightOfferIds") @field:Json(name = "flightOfferIds") var flightOfferIds: List<String>? = null
)
