/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
* general remark type
* Values: GENERAL_MISCELLANEOUS,CONFIDENTIAL,INVOICE,QUALITY_CONTROL,BACKOFFICE,FULFILLMENT,ITINERARY,TICKETING_MISCELLANEOUS
*/
@JsonClass(generateAdapter = false)
enum class GeneralRemarkType(val value: String) {
    @Json(name = "GENERAL_MISCELLANEOUS") GENERAL_MISCELLANEOUS("GENERAL_MISCELLANEOUS"),
    @Json(name = "CONFIDENTIAL") CONFIDENTIAL("CONFIDENTIAL"),
    @Json(name = "INVOICE") INVOICE("INVOICE"),
    @Json(name = "QUALITY_CONTROL") QUALITY_CONTROL("QUALITY_CONTROL"),
    @Json(name = "BACKOFFICE") BACKOFFICE("BACKOFFICE"),
    @Json(name = "FULFILLMENT") FULFILLMENT("FULFILLMENT"),
    @Json(name = "ITINERARY") ITINERARY("ITINERARY"),
    @Json(name = "TICKETING_MISCELLANEOUS") TICKETING_MISCELLANEOUS("TICKETING_MISCELLANEOUS")
}
