/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Offers Search
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property currencyCode The currency code, as defined in [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217), to reflect the currency in which this amount is expressed.
 * @property originDestinations Origins and Destinations must be properly ordered in time (chronological order in accordance with the timezone of each location) to describe the journey consistently. Dates and times must not be past nor more than 365 days in the future, according to provider settings.Number of Origins and Destinations must not exceed the limit defined in provider settings.
 * @property travelers
 * @property sources Allows enable one or more sources. If present in the list, these sources will be called by the system.
 * @property searchCriteria
 */
@JsonClass(generateAdapter = true)
data class GetFlightOffersQuery(
    @Json(name = "originDestinations") @field:Json(name = "originDestinations") var originDestinations: List<OriginDestination>,
    @Json(name = "travelers") @field:Json(name = "travelers") var travelers: List<Traveler>,
    @Json(name = "sources") @field:Json(name = "sources") var sources: List<FlightOfferSource>,
    @Json(name = "currencyCode") @field:Json(name = "currencyCode") var currencyCode: String? = null,
    @Json(name = "searchCriteria") @field:Json(name = "searchCriteria") var searchCriteria: SearchCriteria? = null
)
