/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Offers Price
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property `data`
 */
@JsonClass(generateAdapter = true)
data class GetPriceQuery(
    @Json(name = "data") @field:Json(name = "data") var `data`: FlightOfferPricingInput
)
