/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Offers Price
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property creditCardFees Map of fee applied by credit card brand
 * @property bags Map of fee applied by bag option
 * @property other-services Map of fee applied by service
 */
@JsonClass(generateAdapter = true)
data class IncludedResourcesMap(
    @Json(name = "creditCardFees") @field:Json(name = "creditCardFees") var creditCardFees: Map<String, Any?>? = null,
    @Json(name = "bags") @field:Json(name = "bags") var bags: Map<String, Any?>? = null,
    @Json(name = "other-services") @field:Json(name = "other-services") var otherServices: Map<String, Any?>? = null
)
