/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property duration duration in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) PnYnMnDTnHnMnS format, e.g. PT2H10M for a duration of 2h10m
 * @property segments
 */
@JsonClass(generateAdapter = true)
data class Itineraries(
    @Json(name = "segments") @field:Json(name = "segments") var segments: List<Segment>,
    @Json(name = "duration") @field:Json(name = "duration") var duration: String? = null
)
