/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Inspiration Search
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property cityCode City code associated to the airport
 * @property countryCode Country code of the airport
 * @property subType Location type: airport or city
 * @property detailedName Name of the location
 */
@JsonClass(generateAdapter = true)
data class LocationValue(
    @Json(name = "cityCode") @field:Json(name = "cityCode") var cityCode: String? = null,
    @Json(name = "countryCode") @field:Json(name = "countryCode") var countryCode: String? = null,
    @Json(name = "subType") @field:Json(name = "subType") var subType: LocationValue.SubTypeEnum? = null,
    @Json(name = "detailedName") @field:Json(name = "detailedName") var detailedName: String? = null
) {
    /**
     * location type: airport or city
     * Values: AIRPORT, CITY
     */
    @JsonClass(generateAdapter = false)
    enum class SubTypeEnum(val value: String) {
        @Json(name = "AIRPORT") AIRPORT("AIRPORT"),
        @Json(name = "CITY") CITY("CITY")
    }
}
