/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * loyalty program information
 * @property programOwner loyalty program airline code
 * @property id loyalty program number
 */
@JsonClass(generateAdapter = true)
data class LoyaltyProgram(
    @Json(name = "programOwner") @field:Json(name = "programOwner") var programOwner: String? = null,
    @Json(name = "id") @field:Json(name = "id") var id: String? = null
)
