/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Inspiration Search
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property currency the currency in which the prices of the flight offers are returned. Currency is specified in the [ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) format, e.g. EUR for Euro
 * @property links
 * @property defaults
 */
@JsonClass(generateAdapter = true)
data class Meta(
    @Json(name = "currency") @field:Json(name = "currency") var currency: String? = null,
    @Json(name = "links") @field:Json(name = "links") var links: Links? = null,
    @Json(name = "defaults") @field:Json(name = "defaults") var defaults: Defaults? = null
)
