/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Choice Prediction
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 * @property services
 * @property price
 * @property pricePerAdult
 * @property pricePerInfant
 * @property pricePerChild
 * @property pricePerSenior
 */
@JsonClass(generateAdapter = true)
data class OfferItem(
    @Json(name = "services") @field:Json(name = "services") var services: List<Service>? = null,
    @Json(name = "price") @field:Json(name = "price") var price: Price? = null,
    @Json(name = "pricePerAdult") @field:Json(name = "pricePerAdult") var pricePerAdult: Price? = null,
    @Json(name = "pricePerInfant") @field:Json(name = "pricePerInfant") var pricePerInfant: Price? = null,
    @Json(name = "pricePerChild") @field:Json(name = "pricePerChild") var pricePerChild: Price? = null,
    @Json(name = "pricePerSenior") @field:Json(name = "pricePerSenior") var pricePerSenior: Price? = null
)

