/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Offers Search
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property originDestinationId
 * @property flightOfferIds
 */
@JsonClass(generateAdapter = true)
data class OneWayCombinations(
    @Json(name = "originDestinationId") @field:Json(name = "originDestinationId") var originDestinationId: String? = null,
    @Json(name = "flightOfferIds") @field:Json(name = "flightOfferIds") var flightOfferIds: List<String>? = null
)
