/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Offers Price
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * information about the operating flight
 * @property carrierCode providing the airline / carrier code
 * @property number the flight number as assigned by the carrier
 * @property suffix the flight number suffix as assigned by the carrier
 */
@JsonClass(generateAdapter = true)
data class OperatingFlight(
    @Json(name = "carrierCode") @field:Json(name = "carrierCode") var carrierCode: String? = null,
    @Json(name = "number") @field:Json(name = "number") var number: String? = null,
    @Json(name = "suffix") @field:Json(name = "suffix") var suffix: String? = null
)
