/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Offers Search
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import java.math.BigDecimal

/**
 * @property id
 * @property originLocationCode Origin location, such as a city or an airport. Currently, only the locations defined in [IATA](http://www.iata.org/publications/Pages/code-search.aspx) are supported.
 * @property originRadius Include other possible locations around the point, located less than this distance in kilometers away. Max:300
 * @property alternativeOriginsCodes Set of alternative origin location, such as a city or an airport. Currently, only the locations defined in [IATA](http://www.iata.org/publications/Pages/code-search.aspx) are supported.
 * @property destinationLocationCode Destination location, such as a city or an airport. Currently, only the locations defined in [IATA](http://www.iata.org/publications/Pages/code-search.aspx) are supported.
 * @property destinationRadius Include other possible locations around the point, located less than this distance in kilometers away. Max:300
 * @property alternativeDestinationsCodes Set of alternative destination location, such as a city or an airport. Currently, only the locations defined in [IATA](http://www.iata.org/publications/Pages/code-search.aspx) are supported.
 * @property departureDateTimeRange Approximate date and time of departure, specified as a local date and time range.
 * @property arrivalDateTimeRange Approximate date and time of arrival, specified as a local date and time range.
 * @property includedConnectionPoints List of included connections points. When an includedViaPoints option is specified, all FlightOffer returned must at least go via this Connecting Point. Currently, only the locations defined in IATA are supported. Used only by the AMADEUS provider
 * @property excludedConnectionPoints List of excluded connections points. Any FlightOffer with these connections points will be present in response. Currently, only the locations defined in IATA are supported. Used only by the AMADEUS provider
 */
@JsonClass(generateAdapter = true)
data class OriginDestination(
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "originLocationCode") @field:Json(name = "originLocationCode") var originLocationCode: String? = null,
    @Json(name = "originRadius") @field:Json(name = "originRadius") var originRadius: BigDecimal? = null,
    @Json(name = "alternativeOriginsCodes") @field:Json(name = "alternativeOriginsCodes") var alternativeOriginsCodes: List<String>? = null,
    @Json(name = "destinationLocationCode") @field:Json(name = "destinationLocationCode") var destinationLocationCode: String? = null,
    @Json(name = "destinationRadius") @field:Json(name = "destinationRadius") var destinationRadius: BigDecimal? = null,
    @Json(name = "alternativeDestinationsCodes") @field:Json(name = "alternativeDestinationsCodes") var alternativeDestinationsCodes: List<String>? = null,
    @Json(name = "departureDateTimeRange") @field:Json(name = "departureDateTimeRange") var departureDateTimeRange: DateTimeRange? = null,
    @Json(name = "arrivalDateTimeRange") @field:Json(name = "arrivalDateTimeRange") var arrivalDateTimeRange: DateTimeRange? = null,
    @Json(name = "includedConnectionPoints") @field:Json(name = "includedConnectionPoints") var includedConnectionPoints: List<String>? = null,
    @Json(name = "excludedConnectionPoints") @field:Json(name = "excludedConnectionPoints") var excludedConnectionPoints: List<String>? = null
)
