/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * departure or arrival information
 * @property iataCode [IATA airline codes](http://www.iata.org/publications/Pages/code-search.aspx)
 * @property terminal terminal name / number
 */
@JsonClass(generateAdapter = true)
data class OriginalFlightEndPoint(
    @Json(name = "iataCode") @field:Json(name = "iataCode") var iataCode: String? = null,
    @Json(name = "terminal") @field:Json(name = "terminal") var terminal: String? = null
)
