/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * details of stops for direct or change of gauge flights
 * @property iataCode [IATA airline codes](http://www.iata.org/publications/Pages/code-search.aspx)
 * @property duration stop duration in [ISO8601](https://en.wikipedia.org/wiki/ISO_8601) PnYnMnDTnHnMnS format, e.g. PT2H10M
 */
@JsonClass(generateAdapter = true)
data class OriginalFlightStop(
    @Json(name = "iataCode") @field:Json(name = "iataCode") var iataCode: String? = null,
    @Json(name = "duration") @field:Json(name = "duration") var duration: String? = null
)
