/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
* other payment method
* Values: ACCOUNT,CHECK,CASH,NONREFUNDABLE
*/
@JsonClass(generateAdapter = false)
enum class OtherPaymentMethod(val value: String) {
    @Json(name = "ACCOUNT") ACCOUNT("ACCOUNT"),
    @Json(name = "CHECK") CHECK("CHECK"),
    @Json(name = "CASH") CASH("CASH"),
    @Json(name = "NONREFUNDABLE") NONREFUNDABLE("NONREFUNDABLE")
}
