/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Check-in Links
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property description parameter descriptive information
 * @property type type of the parameter
 * @property format format of the parameter
 */
@JsonClass(generateAdapter = true)
data class Parameter(
    @Json(name = "type") @field:Json(name = "type") var type: String,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null,
    @Json(name = "format") @field:Json(name = "format") var format: String? = null
)
