/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Offers Price
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property travelerId Id of the traveler
 * @property genderRequired If true, the gender is required for the concerned traveler for the creation of the flight-order
 * @property documentRequired If true, a document is required for the concerned traveler for the creation of the flight-order
 * @property documentIssuanceCityRequired If true, the isuance city of the document is required for the concerned traveler for the creation of the flight-order
 * @property dateOfBirthRequired If true, the date of bitrth is required for the concerned traveler for the creation of the flight-order
 * @property redressRequiredIfAny If true, the redress is required if any for the concerned traveler for the creation of the flight-order
 * @property airFranceDiscountRequired If true, the Air France discount is required for the concerned traveler for the creation of the flight-order
 * @property spanishResidentDiscountRequired If true, the Spanish resident discount is required for the concerned traveler for the creation of the flight-order
 * @property residenceRequired If true, the address is required for the concerned traveler for the creation of the flight-order
 */
@JsonClass(generateAdapter = true)
data class PassengerConditions(
    @Json(name = "travelerId") @field:Json(name = "travelerId") var travelerId: String? = null,
    @Json(name = "genderRequired") @field:Json(name = "genderRequired") var genderRequired: Boolean? = null,
    @Json(name = "documentRequired") @field:Json(name = "documentRequired") var documentRequired: Boolean? = null,
    @Json(name = "documentIssuanceCityRequired") @field:Json(name = "documentIssuanceCityRequired") var documentIssuanceCityRequired: Boolean? = null,
    @Json(name = "dateOfBirthRequired") @field:Json(name = "dateOfBirthRequired") var dateOfBirthRequired: Boolean? = null,
    @Json(name = "redressRequiredIfAny") @field:Json(name = "redressRequiredIfAny") var redressRequiredIfAny: Boolean? = null,
    @Json(name = "airFranceDiscountRequired") @field:Json(name = "airFranceDiscountRequired") var airFranceDiscountRequired: Boolean? = null,
    @Json(name = "spanishResidentDiscountRequired") @field:Json(name = "spanishResidentDiscountRequired") var spanishResidentDiscountRequired: Boolean? = null,
    @Json(name = "residenceRequired") @field:Json(name = "residenceRequired") var residenceRequired: Boolean? = null
)
