/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
* Type of the device (Landline, Mobile or Fax)
* Values: MOBILE,LANDLINE,FAX
*/
@JsonClass(generateAdapter = false)
enum class PhoneDeviceType(val value: String) {
    @Json(name = "MOBILE") MOBILE("MOBILE"),
    @Json(name = "LANDLINE") LANDLINE("LANDLINE"),
    @Json(name = "FAX") FAX("FAX")
}
