/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Offers Price
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * price information
 * @property currency
 * @property total Total amount paid by the user
 * @property totalTaxes
 * @property base Amount without taxes
 * @property fees List of applicable fees
 * @property taxes
 * @property refundableTaxes The amount of taxes which are refundable
 * @property margin BOOK step ONLY - The price margin percentage (plus or minus) that the booking can tolerate. When set to 0, then no price magin is tolerated.
 * @property grandTotal Total amount paid by the user (including fees and selected additional services).
 * @property billingCurrency Currency of the payment. It may be different than the requested currency
 * @property additionalServices
 */
@JsonClass(generateAdapter = true)
data class Price(
    @Json(name = "currency") @field:Json(name = "currency") var currency: String? = null,
    @Json(name = "total") @field:Json(name = "total") var total: String? = null,
    @Json(name = "totalTaxes") @field:Json(name = "totalTaxes") var totalTaxes: String? = null,
    @Json(name = "base") @field:Json(name = "base") var base: String? = null,
    @Json(name = "fees") @field:Json(name = "fees") var fees: List<Fee>? = null,
    @Json(name = "taxes") @field:Json(name = "taxes") var taxes: List<Tax>? = null,
    @Json(name = "refundableTaxes") @field:Json(name = "refundableTaxes") var refundableTaxes: String? = null,
    @Json(name = "margin") @field:Json(name = "margin") var margin: String? = null,
    @Json(name = "grandTotal") @field:Json(name = "grandTotal") var grandTotal: String? = null,
    @Json(name = "billingCurrency") @field:Json(name = "billingCurrency") var billingCurrency: String? = null,
    @Json(name = "additionalServices") @field:Json(name = "additionalServices") var additionalServices: List<AdditionalService>? = null
)
