/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Identifies the queue onto which PNR must be automatically placed upon process execution.
 * @property number
 * @property category
 */
@JsonClass(generateAdapter = true)
data class Queue(
    @Json(name = "number") @field:Json(name = "number") var number: String? = null,
    @Json(name = "category") @field:Json(name = "category") var category: String? = null
)
