/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Seatmap Display
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property travelerId Traveler id
 * @property seatAvailabilityStatus Seat availability for this specific traveler. Allows better seat choice per traveler
 * @property price Price for a given seat
 */
@JsonClass(generateAdapter = true)
data class SeatmapTravelerPricing(
    @Json(name = "travelerId") @field:Json(name = "travelerId") var travelerId: String? = null,
    @Json(name = "seatAvailabilityStatus") @field:Json(name = "seatAvailabilityStatus") var seatAvailabilityStatus: SeatmapTravelerPricing.SeatAvailabilityStatusEnum? = null,
    @Json(name = "price") @field:Json(name = "price") var price: Price? = null
) {
    /**
     * Seat availability for this specific traveler. Allows better seat choice per traveler
     * Values: AVAILABLE, BLOCKED, OCCUPIED
     */
    @JsonClass(generateAdapter = false)
    enum class SeatAvailabilityStatusEnum(val value: String) {
        @Json(name = "AVAILABLE") AVAILABLE("AVAILABLE"),
        @Json(name = "BLOCKED") BLOCKED("BLOCKED"),
        @Json(name = "OCCUPIED") OCCUPIED("OCCUPIED")
    }
}
