/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Order Management
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
* type of service
* Values: PRIORITY_BOARDING,AIRPORT_CHECKIN
*/
@JsonClass(generateAdapter = false)
enum class ServiceName(val value: String) {
    @Json(name = "PRIORITY_BOARDING") PRIORITY_BOARDING("PRIORITY_BOARDING"),
    @Json(name = "AIRPORT_CHECKIN") AIRPORT_CHECKIN("AIRPORT_CHECKIN")
}
