/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Offers Price
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property segments
 * @property name
 * @property price
 * @property bookableByTraveler Specify if the service is bookable by traveler or for all travelers
 * @property bookableByItinerary Specify if the service is bookable by itinerary or for all itineraries
 * @property segmentIds Id of the segment concerned by the service
 * @property travelerIds Id of the traveler concerned by the service
 */
@JsonClass(generateAdapter = true)
data class Service(
    @Json(name = "segments") @field:Json(name = "segments") var segments: List<Segment>? = null,
    @Json(name = "name") @field:Json(name = "name") var name: ServiceName? = null,
    @Json(name = "price") @field:Json(name = "price") var price: ElementaryPrice? = null,
    @Json(name = "bookableByTraveler") @field:Json(name = "bookableByTraveler") var bookableByTraveler: Boolean? = null,
    @Json(name = "bookableByItinerary") @field:Json(name = "bookableByItinerary") var bookableByItinerary: Boolean? = null,
    @Json(name = "segmentIds") @field:Json(name = "segmentIds") var segmentIds: List<String>? = null,
    @Json(name = "travelerIds") @field:Json(name = "travelerIds") var travelerIds: List<String>? = null
)
