/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
* slice and Dice indicator, such as Local Availability, Sub OnD(Origin and Destination) 1 Availability and Sub OnD 2 Availability
* Values: LOCAL_AVAILABILITY,SUB_OD_AVAILABILITY_1,SUB_OD_AVAILABILITY_2
*/
@JsonClass(generateAdapter = false)
enum class SliceDiceIndicator(val value: String) {
    @Json(name = "LOCAL_AVAILABILITY") LOCAL_AVAILABILITY("LOCAL_AVAILABILITY"),
    @Json(name = "SUB_OD_AVAILABILITY_1") SUB_OD_AVAILABILITY_1("SUB_OD_AVAILABILITY_1"),
    @Json(name = "SUB_OD_AVAILABILITY_2") SUB_OD_AVAILABILITY_2("SUB_OD_AVAILABILITY_2")
}
