/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
* The gender
* Values: MALE,FEMALE
*/
@JsonClass(generateAdapter = false)
enum class StakeholderGender(val value: String) {
    @Json(name = "MALE") MALE("MALE"),
    @Json(name = "FEMALE") FEMALE("FEMALE")
}
