/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Order Management
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property category This defines what type of modification is concerned in this rule.
 * @property circumstances
 * @property notApplicable
 * @property maxPenaltyAmount
 * @property descriptions
 */
@JsonClass(generateAdapter = true)
data class TermAndCondition(
    @Json(name = "category") @field:Json(name = "category") var category: TermAndCondition.CategoryEnum? = null,
    @Json(name = "circumstances") @field:Json(name = "circumstances") var circumstances: String? = null,
    @Json(name = "notApplicable") @field:Json(name = "notApplicable") var notApplicable: Boolean? = null,
    @Json(name = "maxPenaltyAmount") @field:Json(name = "maxPenaltyAmount") var maxPenaltyAmount: String? = null,
    @Json(name = "descriptions") @field:Json(name = "descriptions") var descriptions: List<Description>? = null
) {
    /**
     * This defines what type of modification is concerned in this rule.
     * Values: REFUND, EXCHANGE, REVALIDATION, REISSUE, REBOOK, CANCELLATION
     */
    @JsonClass(generateAdapter = false)
    enum class CategoryEnum(val value: String) {
        @Json(name = "REFUND") REFUND("REFUND"),
        @Json(name = "EXCHANGE") EXCHANGE("EXCHANGE"),
        @Json(name = "REVALIDATION") REVALIDATION("REVALIDATION"),
        @Json(name = "REISSUE") REISSUE("REISSUE"),
        @Json(name = "REBOOK") REBOOK("REBOOK"),
        @Json(name = "CANCELLATION") CANCELLATION("CANCELLATION")
    }
}
