/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Order Management
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
* ticketing agreement option
* Values: CONFIRM,DELAY_TO_QUEUE,DELAY_TO_CANCEL,AIRLINE_UNTICKETED_CANCELATION
*/
@JsonClass(generateAdapter = false)
enum class TicketingAgreementOption(val value: String) {
    @Json(name = "CONFIRM") CONFIRM("CONFIRM"),
    @Json(name = "DELAY_TO_QUEUE") DELAY_TO_QUEUE("DELAY_TO_QUEUE"),
    @Json(name = "DELAY_TO_CANCEL") DELAY_TO_CANCEL("DELAY_TO_CANCEL"),
    @Json(name = "AIRLINE_UNTICKETED_CANCELATION") AIRLINE_UNTICKETED_CANCELATION("AIRLINE_UNTICKETED_CANCELATION")
}
