/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Order Management
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * ticketing agreement
 * @property option
 * @property delay Delay before applying automatic process if no issuance in days
 * @property dateTime Exact date to apply automatic process if no issuance. YYYY-MM-DD format, e.g. 2019-06-07
 * @property segmentIds Ids of the impacted segments
 */
@JsonClass(generateAdapter = true)
data class TicketingAgreement(
    @Json(name = "option") @field:Json(name = "option") var option: TicketingAgreementOption? = null,
    @Json(name = "delay") @field:Json(name = "delay") var delay: String? = null,
    @Json(name = "dateTime") @field:Json(name = "dateTime") var dateTime: String? = null,
    @Json(name = "segmentIds") @field:Json(name = "segmentIds") var segmentIds: List<String>? = null
)
