/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.LocalDate

/**
 * the traveler of the trip
 * @property id item identifier
 * @property dateOfBirth The date of birth in ISO 8601 format (yyyy-mm-dd)
 * @property gender
 * @property name
 * @property documents Advanced Passenger Information - regulatory identity documents - SSR DOCS &amp; DOCO elements
 * @property emergencyContact emergency contact
 * @property loyaltyPrograms list of loyalty program followed by the traveler
 * @property discountEligibility list of element that allow a discount.
 * @property contact
 */
@JsonClass(generateAdapter = true)
data class TravelerElement(
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "dateOfBirth") @field:Json(name = "dateOfBirth") var dateOfBirth: LocalDate? = null,
    @Json(name = "gender") @field:Json(name = "gender") var gender: StakeholderGender? = null,
    @Json(name = "name") @field:Json(name = "name") var name: Name? = null,
    @Json(name = "documents") @field:Json(name = "documents") var documents: List<TravelerDocuments>? = null,
    @Json(name = "emergencyContact") @field:Json(name = "emergencyContact") var emergencyContact: EmergencyContact? = null,
    @Json(name = "loyaltyPrograms") @field:Json(name = "loyaltyPrograms") var loyaltyPrograms: List<LoyaltyProgram>? = null,
    @Json(name = "discountEligibility") @field:Json(name = "discountEligibility") var discountEligibility: List<Discount>? = null,
    @Json(name = "contact") @field:Json(name = "contact") var contact: Contact? = null
)
