/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property travelerId Id of the traveler
 * @property fareOption
 * @property travelerType
 * @property associatedAdultId if type&#x3D;\&quot;HELD_INFANT\&quot;, corresponds to the adult traveler&#39;s id who will share the seat
 * @property price price detail of the traveler
 * @property fareDetailsBySegment
 */
@JsonClass(generateAdapter = true)
data class TravelerPricing(
    @Json(name = "travelerId") @field:Json(name = "travelerId") var travelerId: String,
    @Json(name = "fareOption") @field:Json(name = "fareOption") var fareOption: TravelerPricingFareOption? = null,
    @Json(name = "travelerType") @field:Json(name = "travelerType") var travelerType: TravelerType,
    @Json(name = "fareDetailsBySegment") @field:Json(name = "fareDetailsBySegment") var fareDetailsBySegment: List<FareDetailsBySegment>,
    @Json(name = "associatedAdultId") @field:Json(name = "associatedAdultId") var associatedAdultId: String? = null,
    @Json(name = "price") @field:Json(name = "price") var price: Price? = null
)
