/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Seatmap Display
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property travelers Map of travelers
 */
@JsonClass(generateAdapter = true)
data class TravelersMap(
    @Json(name = "travelers") @field:Json(name = "travelers") var travelers: Map<String, Any?>? = null
)
