/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Flight Create Orders
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.air.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * detail information of the virtual card
 * @property brand
 * @property holder card holder as on the card
 * @property number card number
 * @property expiryDate credit card expiration date following [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) (YYYY-MM format, e.g. 2012-08)
 * @property amount Amount of the fare. could be alpha numeric. Ex- 500.20 or 514.13A, &#39;A&#39;signifies additional collection.
 * @property currencyCode Currency type of the fare.
 */
@JsonClass(generateAdapter = true)
data class VirtualCreditCardDetails(
    @Json(name = "brand") @field:Json(name = "brand") var brand: CreditCardBrand? = null,
    @Json(name = "holder") @field:Json(name = "holder") var holder: String? = null,
    @Json(name = "number") @field:Json(name = "number") var number: String? = null,
    @Json(name = "expiryDate") @field:Json(name = "expiryDate") var expiryDate: String? = null,
    @Json(name = "amount") @field:Json(name = "amount") var amount: String? = null,
    @Json(name = "currencyCode") @field:Json(name = "currencyCode") var currencyCode: String? = null
)
