/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Address Details
 * @property lines When the address is unformatted these lines will contain free form address details.
 * @property postalCode Post office code number
 * @property cityName City Name
 * @property countryCode ISO 3166-1 defines codes for the names of countries, dependent territories, and special areas of geographical interest
 * @property stateCode ISO 3166-2 defines codes for identifying the principal subdivisions (e.g. provinces or states) of all countries coded in ISO 3166-1
 */
@JsonClass(generateAdapter = true)
data class AddressHotel(
    @Json(name = "lines") @field:Json(name = "lines") var lines: List<String>? = null,
    @Json(name = "postalCode") @field:Json(name = "postalCode") var postalCode: String? = null,
    @Json(name = "cityName") @field:Json(name = "cityName") var cityName: String? = null,
    @Json(name = "countryCode") @field:Json(name = "countryCode") var countryCode: String? = null,
    @Json(name = "stateCode") @field:Json(name = "stateCode") var stateCode: String? = null
)
