/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel Booking
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Address Details
 * @property lines Address Lines
 * @property cityName City Name
 * @property postalCode Zip/Post Code
 * @property stateCode State Code. ISO 3166-2 defines codes for identifying the principal subdivisions (e.g. provinces or states) of all countries coded in ISO 3166-1
 * @property countryCode Country Code in ISO 3166-1 format
 */
@JsonClass(generateAdapter = true)
data class Address(
    @Json(name = "lines") @field:Json(name = "lines") var lines: List<String>,
    @Json(name = "cityName") @field:Json(name = "cityName") var cityName: String,
    @Json(name = "countryCode") @field:Json(name = "countryCode") var countryCode: String,
    @Json(name = "postalCode") @field:Json(name = "postalCode") var postalCode: String? = null,
    @Json(name = "stateCode") @field:Json(name = "stateCode") var stateCode: String? = null
)
