/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * estimated nightly average for the stay
 * @property base Amount excluding taxes.
 * @property total Amount including taxes.
 */
@JsonClass(generateAdapter = true)
data class BaseTotalAmount(
    @Json(name = "base") @field:Json(name = "base") var base: String?,
    @Json(name = "total") @field:Json(name = "total") var total: String?
)
