/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel Booking
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property offerId offerId to book
 * @property guests minimum one guest is mandatory
 * @property payments payments (often mandatory)
 * @property rooms rooms repartition (when used the &#x60;rooms&#x60; array items must match the shopping offer &#x60;roomQuantity&#x60;)
 */
@JsonClass(generateAdapter = true)
data class BookinghotelbookingsData(
    @Json(name = "offerId") @field:Json(name = "offerId") var offerId: String,
    @Json(name = "guests") @field:Json(name = "guests") var guests: List<Stakeholder>,
    @Json(name = "payments") @field:Json(name = "payments") var payments: List<Payment>? = null,
    @Json(name = "rooms") @field:Json(name = "rooms") var rooms: List<BookinghotelbookingsDataRooms>? = null
)
