/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.ZonedDateTime

/**
 * @property type [\&quot;Flat\&quot;,\&quot;FlatPerNight\&quot;, \&quot;Nights\&quot;, \&quot;StayPercent\&quot;, \&quot;FirstNight\&quot;, \&quot;LastNight\&quot;, \&quot;FirstAndLastNight\&quot;, \&quot;FullStay\&quot;] Several penalty types can apply for the same product. 
 * @property amount Amount of the cancellation fee.
 * @property numberOfNights Number of nights due as fee in case of cancellation.
 * @property percentage Percentage of the total stay amount to be paid in case of cancellation. Value is between 0 and 100.
 * @property deadline Represents the deadline&#39;s date. Time is in ISO 8601 [https://www.w3.org/TR/NOTE-datetime]. Example: 2010-08-14T13:00:00 Please note that this value is expressed in the hotels local time zone 
 * @property description
 */
@JsonClass(generateAdapter = true)
data class CancellationPolicy(
    @Json(name = "type") @field:Json(name = "type") var type: String? = null,
    @Json(name = "amount") @field:Json(name = "amount") var amount: String? = null,
    @Json(name = "numberOfNights") @field:Json(name = "numberOfNights") var numberOfNights: Int? = null,
    @Json(name = "percentage") @field:Json(name = "percentage") var percentage: String? = null,
    @Json(name = "deadline") @field:Json(name = "deadline") var deadline: ZonedDateTime? = null,
    @Json(name = "description") @field:Json(name = "description") var description: TextWithLanguageType? = null
)
