/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property checkIn Check-in From time limit in ISO-8601 format [http://www.w3.org/TR/xmlschema-2/#time]
 * @property checkInDescription
 * @property checkOut Check-out Until time limit in ISO-8601 format [http://www.w3.org/TR/xmlschema-2/#time]
 * @property checkOutDescription
 */
@JsonClass(generateAdapter = true)
data class CheckInOutPolicy(
    @Json(name = "checkIn") @field:Json(name = "checkIn") var checkIn: String? = null,
    @Json(name = "checkInDescription") @field:Json(name = "checkInDescription") var checkInDescription: TextWithLanguageType? = null,
    @Json(name = "checkOut") @field:Json(name = "checkOut") var checkOut: String? = null,
    @Json(name = "checkOutDescription") @field:Json(name = "checkOutDescription") var checkOutDescription: TextWithLanguageType? = null
)
