/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property percentage Percentage of the commission paid to the travel seller. Value is between 0 and 100
 * @property amount Amount of the commission paid to the travel seller. The amount is always linked to the currency code of the offer
 * @property description
 */
@JsonClass(generateAdapter = true)
data class Commission(
    @Json(name = "percentage") @field:Json(name = "percentage") var percentage: String? = null,
    @Json(name = "amount") @field:Json(name = "amount") var amount: String? = null,
    @Json(name = "description") @field:Json(name = "description") var description: TextWithLanguageType? = null
)
