/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Contact Details
 * @property phone Phone Number
 * @property fax Fax Number
 * @property email Email Address
 */
@JsonClass(generateAdapter = true)
data class ContactHotel(
    @Json(name = "phone") @field:Json(name = "phone") var phone: String,
    @Json(name = "fax") @field:Json(name = "fax") var fax: String,
    @Json(name = "email") @field:Json(name = "email") var email: String? = null
)
