/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel Booking
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Contact Details
 * @property phone Phone Number in standard E.123(https://en.wikipedia.org/wiki/E.123)
 * @property email Email Address
 */
@JsonClass(generateAdapter = true)
data class Contact(
    @Json(name = "phone") @field:Json(name = "phone") var phone: String,
    @Json(name = "email") @field:Json(name = "email") var email: String
)
