/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * conversion from provider's currency to requested currency
 * @property rate The conversion factor to apply against the source currency to obtain the requested currency
 * @property target Requested currency code
 * @property targetDecimalPlaces Indicates the number of decimal places for the target currency
 */
@JsonClass(generateAdapter = true)
data class CurrencyConversionRate(
    @Json(name = "rate") @field:Json(name = "rate") var rate: String? = null,
    @Json(name = "target") @field:Json(name = "target") var target: String? = null,
    @Json(name = "targetDecimalPlaces") @field:Json(name = "targetDecimalPlaces") var targetDecimalPlaces: Int? = null
)
