/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * estimated room category, bed type and number of beds in the room. This information has been parsed from the room description, and is thus only provided for informational purposes
 * @property category Category code
 * @property beds Number of beds in the room (1-9)
 * @property bedType Type of the bed
 */
@JsonClass(generateAdapter = true)
data class EstimatedRoomType(
    @Json(name = "category") @field:Json(name = "category") var category: String? = null,
    @Json(name = "beds") @field:Json(name = "beds") var beds: Int? = null,
    @Json(name = "bedType") @field:Json(name = "bedType") var bedType: String? = null
)
