/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * the guarantee policy information applicable to the offer. It includes accepted payments
 * @property description
 * @property acceptedPayments
 */
@JsonClass(generateAdapter = true)
data class GuaranteePolicy(
    @Json(name = "description") @field:Json(name = "description") var description: TextWithLanguageType? = null,
    @Json(name = "acceptedPayments") @field:Json(name = "acceptedPayments") var acceptedPayments: PaymentPolicy? = null
)
