/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property currencyConversionLookupRates - Used to convey rate conversions the requested currency differs from the currency returned by a hotel - origin_amount &#x3D; reverse_rate x target_amount - target_amount &#x3D; rate x origin_amount - Example:         currencyConversionLookupRates: {           USD: {                 rate: \&quot;0.80\&quot;,                 targetDecimalPlaces: 2,                 target: EUR             },             GBP: {                 rate: \&quot;1.14\&quot;,                 targetDecimalPlaces: 2,                 target: EUR             }         } 
 */
@JsonClass(generateAdapter = true)
data class HotelDictionary(
    @Json(name = "currencyConversionLookupRates") @field:Json(name = "currencyConversionLookupRates") var currencyConversionLookupRates: Map<String, CurrencyConversionRate>? = null
)
