/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel Ratings
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Dictionary containing scores for all the available categories.  If a property does not have any category this object will not be present in the response.
 * @property sleepQuality
 * @property service
 * @property facilities
 * @property roomComforts
 * @property valueForMoney
 * @property catering
 * @property swimmingPool
 * @property location
 * @property internet
 * @property pointsOfInterest
 * @property staff
 */
@JsonClass(generateAdapter = true)
data class HotelSentimentSentiments(
    @Json(name = "sleepQuality") @field:Json(name = "sleepQuality") var sleepQuality: Score? = null,
    @Json(name = "service") @field:Json(name = "service") var service: Score? = null,
    @Json(name = "facilities") @field:Json(name = "facilities") var facilities: Score? = null,
    @Json(name = "roomComforts") @field:Json(name = "roomComforts") var roomComforts: Score? = null,
    @Json(name = "valueForMoney") @field:Json(name = "valueForMoney") var valueForMoney: Score? = null,
    @Json(name = "catering") @field:Json(name = "catering") var catering: Score? = null,
    @Json(name = "swimmingPool") @field:Json(name = "swimmingPool") var swimmingPool: Score? = null,
    @Json(name = "location") @field:Json(name = "location") var location: Score? = null,
    @Json(name = "internet") @field:Json(name = "internet") var internet: Score? = null,
    @Json(name = "pointsOfInterest") @field:Json(name = "pointsOfInterest") var pointsOfInterest: Score? = null,
    @Json(name = "staff") @field:Json(name = "staff") var staff: Score? = null
)
