/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * price information
 * @property currency Currency code
 * @property total Total amount including taxes
 * @property base Total amount excluding taxes
 * @property taxes
 * @property variations
 */
@JsonClass(generateAdapter = true)
data class HotelPrice(
    @Json(name = "currency") @field:Json(name = "currency") var currency: String? = null,
    @Json(name = "total") @field:Json(name = "total") var total: String? = null,
    @Json(name = "base") @field:Json(name = "base") var base: String? = null,
    @Json(name = "taxes") @field:Json(name = "taxes") var taxes: List<PriceTax>? = null,
    @Json(name = "variations") @field:Json(name = "variations") var variations: PriceVariations? = null
)
