/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * details of the requested hotel and the available offers
 * @property type the type of the object (hotel-offers)
 * @property hotel
 * @property available availability status of this hotel
 * @property offers
 * @property self a self link to the object
 */
@JsonClass(generateAdapter = true)
data class HotelOffers(
    @Json(name = "type") @field:Json(name = "type") var type: String? = null,
    @Json(name = "hotel") @field:Json(name = "hotel") var hotel: Hotel? = null,
    @Json(name = "available") @field:Json(name = "available") var available: Boolean? = null,
    @Json(name = "offers") @field:Json(name = "offers") var offers: List<HotelOffer>? = null,
    @Json(name = "self") @field:Json(name = "self") var self: String? = null
)
