/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * distance from the point of search to the hotel
 * @property distance distance (in &#x60;distanceUnit&#x60;)
 * @property distanceUnit unit of measure (Km or Miles)
 */
@JsonClass(generateAdapter = true)
data class HotelDistance(
    @Json(name = "distance") @field:Json(name = "distance") var distance: Double? = null,
    @Json(name = "distanceUnit") @field:Json(name = "distanceUnit") var distanceUnit: HotelDistance.DistanceUnitEnum? = null
) {
    /**
     * unit of measure (Km or Miles)
     * Values: KM, MILE
     */
    @JsonClass(generateAdapter = false)
    enum class DistanceUnitEnum(val value: String) {
        @Json(name = "KM") KM("KM"),
        @Json(name = "MILE") MILE("MILE")
    }
}
