/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.LocalDate

/**
 * Hotel Offer
 * @property type data type
 * @property id Unique identifier of this offer. Might be valid for a temporary period only.
 * @property checkInDate check-in date of the stay (hotel local date). Format YYYY-MM-DD  The lowest accepted value is today date (no dates in the past).   
 * @property checkOutDate check-out date of the stay (hotel local date). Format YYYY-MM-DD  The lowest accepted value is &#x60;checkInDate&#x60;+1.   
 * @property roomQuantity number of rooms (1-9)
 * @property rateCode Special Rate - Provider Response Code (3 chars) Examples: * RAC - Rack * BAR - Best Available Rate * PRO - Promotional * COR - Corporate * GOV - Government (qualified) * AAA - AAA (qualified) * BNB - Bed and Breakfast * PKG - Package * TVL - Travel Industry * SPC - Special Promo Rate * WKD - Weekend * CON - Convention * SNR - Senior (Europe) (qualified) * ARP - AARP - American Association of Retired People (50+) (qualified) * SRS - Senior (qualified) * ROR - Room Only Rate (no breakfast) * FAM - Family * DAY - Day rate 
 * @property rateFamilyEstimated
 * @property category Special Rate Category Examples:  ASSOCIATION  FAMILY_PLAN 
 * @property description
 * @property commission
 * @property boardType The included Breakfast/Meals 
 * @property room
 * @property guests
 * @property price
 * @property policies
 * @property self A self link to the object. Use this to refresh the Offer price
 */
@JsonClass(generateAdapter = true)
data class HotelOffer(
    @Json(name = "id") @field:Json(name = "id") var id: String,
    @Json(name = "rateCode") @field:Json(name = "rateCode") var rateCode: String,
    @Json(name = "room") @field:Json(name = "room") var room: RoomDetails,
    @Json(name = "price") @field:Json(name = "price") var price: HotelPrice,
    @Json(name = "type") @field:Json(name = "type") var type: HotelOffer.TypeEnum? = null,
    @Json(name = "checkInDate") @field:Json(name = "checkInDate") var checkInDate: LocalDate? = null,
    @Json(name = "checkOutDate") @field:Json(name = "checkOutDate") var checkOutDate: LocalDate? = null,
    @Json(name = "roomQuantity") @field:Json(name = "roomQuantity") var roomQuantity: Int? = null,
    @Json(name = "rateFamilyEstimated") @field:Json(name = "rateFamilyEstimated") var rateFamilyEstimated: RateFamily? = null,
    @Json(name = "category") @field:Json(name = "category") var category: String? = null,
    @Json(name = "description") @field:Json(name = "description") var description: TextWithLanguageType? = null,
    @Json(name = "commission") @field:Json(name = "commission") var commission: Commission? = null,
    @Json(name = "boardType") @field:Json(name = "boardType") var boardType: HotelOffer.BoardTypeEnum? = null,
    @Json(name = "guests") @field:Json(name = "guests") var guests: Guests? = null,
    @Json(name = "policies") @field:Json(name = "policies") var policies: PolicyDetails? = null,
    @Json(name = "self") @field:Json(name = "self") var self: String? = null
) {
    /**
     * data type
     * Values: HOTELMINUSOFFER
     */
    @JsonClass(generateAdapter = false)
    enum class TypeEnum(val value: String) {
        @Json(name = "hotel-offer") HOTELMINUSOFFER("hotel-offer")
    }
    /**
     * The included Breakfast/Meals 
     * Values: ROOM_ONLY, BREAKFAST, HALF_BOARD, FULL_BOARD, ALL_INCLUSIVE, BUFFET_BREAKFAST, CARIBBEAN_BREAKFAST, CONTINENTAL_BREAKFAST, ENGLISH_BREAKFAST, FULL_BREAKFAST, DINNER_BED_AND_BREAKFAST, LUNCH, DINNER, FAMILY_PLAN, AS_BROCHURED, SELF_CATERING, BERMUDA, AMERICAN, FAMILY_AMERICAN, MODIFIED
     */
    @JsonClass(generateAdapter = false)
    enum class BoardTypeEnum(val value: String) {
        @Json(name = "ROOM_ONLY") ROOM_ONLY("ROOM_ONLY"),
        @Json(name = "BREAKFAST") BREAKFAST("BREAKFAST"),
        @Json(name = "HALF_BOARD") HALF_BOARD("HALF_BOARD"),
        @Json(name = "FULL_BOARD") FULL_BOARD("FULL_BOARD"),
        @Json(name = "ALL_INCLUSIVE") ALL_INCLUSIVE("ALL_INCLUSIVE"),
        @Json(name = "BUFFET_BREAKFAST") BUFFET_BREAKFAST("BUFFET_BREAKFAST"),
        @Json(name = "CARIBBEAN_BREAKFAST") CARIBBEAN_BREAKFAST("CARIBBEAN_BREAKFAST"),
        @Json(name = "CONTINENTAL_BREAKFAST") CONTINENTAL_BREAKFAST("CONTINENTAL_BREAKFAST"),
        @Json(name = "ENGLISH_BREAKFAST") ENGLISH_BREAKFAST("ENGLISH_BREAKFAST"),
        @Json(name = "FULL_BREAKFAST") FULL_BREAKFAST("FULL_BREAKFAST"),
        @Json(name = "DINNER_BED_AND_BREAKFAST") DINNER_BED_AND_BREAKFAST("DINNER_BED_AND_BREAKFAST"),
        @Json(name = "LUNCH") LUNCH("LUNCH"),
        @Json(name = "DINNER") DINNER("DINNER"),
        @Json(name = "FAMILY_PLAN") FAMILY_PLAN("FAMILY_PLAN"),
        @Json(name = "AS_BROCHURED") AS_BROCHURED("AS_BROCHURED"),
        @Json(name = "SELF_CATERING") SELF_CATERING("SELF_CATERING"),
        @Json(name = "BERMUDA") BERMUDA("BERMUDA"),
        @Json(name = "AMERICAN") AMERICAN("AMERICAN"),
        @Json(name = "FAMILY_AMERICAN") FAMILY_AMERICAN("FAMILY_AMERICAN"),
        @Json(name = "MODIFIED") MODIFIED("MODIFIED")
    }
}
