/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel Ratings
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property hotelId Amadeus Hotel Ids are found in the Hotel Search response (parameter name is &#39;hotelId&#39;)
 * @property type
 * @property overallRating
 * @property numberOfRatings
 * @property numberOfReviews
 * @property sentiments
 */
@JsonClass(generateAdapter = true)
data class HotelSentiment(
    @Json(name = "hotelId") @field:Json(name = "hotelId") var hotelId: String,
    @Json(name = "overallRating") @field:Json(name = "overallRating") var overallRating: Score,
    @Json(name = "numberOfRatings") @field:Json(name = "numberOfRatings") var numberOfRatings: Int,
    @Json(name = "numberOfReviews") @field:Json(name = "numberOfReviews") var numberOfReviews: Int,
    @Json(name = "type") @field:Json(name = "type") var type: String? = null,
    @Json(name = "sentiments") @field:Json(name = "sentiments") var sentiments: HotelSentimentSentiments? = null
)
