/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * links to continue in the shopping process
 * @property next Use this link to get the next hotels in the search result
 */
@JsonClass(generateAdapter = true)
data class Links(
    @Json(name = "next") @field:Json(name = "next") var next: String? = null
)
