/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel Booking
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Guest Name
 * @property title title/gender of room guest
 * @property firstName first name of room guest
 * @property lastName last name of room guest
 */
@JsonClass(generateAdapter = true)
data class Name(
    @Json(name = "firstName") @field:Json(name = "firstName") var firstName: String,
    @Json(name = "lastName") @field:Json(name = "lastName") var lastName: String,
    @Json(name = "title") @field:Json(name = "title") var title: Name.TitleEnum? = null
) {
    /**
     * title/gender of room guest
     * Values: MR, MRS, MS
     */
    @JsonClass(generateAdapter = false)
    enum class TitleEnum(val value: String) {
        @Json(name = "MR") MR("MR"),
        @Json(name = "MRS") MRS("MRS"),
        @Json(name = "MS") MS("MS")
    }
}
