/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel Booking
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * payment card details (mandatory in case of `method` creditCard)
 * @property vendorCode card type (CA, VI, AX, DC...) Examples:   * CA - MasterCard (warning: use it instead of MC/IK/EC/MD/XS)   * VI - Visa   * AX - American Express   * DC - Diners Club   * AU - Carte Aurore   * CG - Cofinoga   * DS - Discover   * GK - Lufthansa GK Card   * JC - Japanese Credit Bureau   * TC - Torch Club   * TP - Universal Air Travel Card   * BC - Bank Card   * DL - Delta   * MA - Maestro   * UP - China UnionPay      * VE - Visa Electron 
 * @property cardNumber card number
 * @property expiryDate Expiration Date YYYY-MM
 */
@JsonClass(generateAdapter = true)
data class PaymentCard(
    @Json(name = "vendorCode") @field:Json(name = "vendorCode") var vendorCode: String,
    @Json(name = "cardNumber") @field:Json(name = "cardNumber") var cardNumber: String,
    @Json(name = "expiryDate") @field:Json(name = "expiryDate") var expiryDate: String
)
