/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Accepted Payment Methods and Card Types. Several Payment Methods and Card Types may be available
 * @property creditCards Accepted Payment Card Types for the &#x60;method&#x60; CREDIT_CARD
 * @property methods Accepted Payment Methods
 */
@JsonClass(generateAdapter = true)
data class PaymentPolicy(
    @Json(name = "creditCards") @field:Json(name = "creditCards") var creditCards: List<String>? = null,
    @Json(name = "methods") @field:Json(name = "methods") var methods: List<PaymentPolicy.MethodsEnum>? = null
) {
    /**
     * Accepted Payment Methods
     * Values: CREDIT_CARD, TRAVEL_AGENT_ID, CORPORATE_ID, HOTEL_GUEST_ID, CHECK, MISC_CHARGE_ORDER, ADVANCE_DEPOSIT, COMPANY_ADDRESS, AGENCY_ACCOUNT
     */
    @JsonClass(generateAdapter = false)
    enum class MethodsEnum(val value: String) {
        @Json(name = "CREDIT_CARD") CREDIT_CARD("CREDIT_CARD"),
        @Json(name = "TRAVEL_AGENT_ID") TRAVEL_AGENT_ID("TRAVEL_AGENT_ID"),
        @Json(name = "CORPORATE_ID") CORPORATE_ID("CORPORATE_ID"),
        @Json(name = "HOTEL_GUEST_ID") HOTEL_GUEST_ID("HOTEL_GUEST_ID"),
        @Json(name = "CHECK") CHECK("CHECK"),
        @Json(name = "MISC_CHARGE_ORDER") MISC_CHARGE_ORDER("MISC_CHARGE_ORDER"),
        @Json(name = "ADVANCE_DEPOSIT") ADVANCE_DEPOSIT("ADVANCE_DEPOSIT"),
        @Json(name = "COMPANY_ADDRESS") COMPANY_ADDRESS("COMPANY_ADDRESS"),
        @Json(name = "AGENCY_ACCOUNT") AGENCY_ACCOUNT("AGENCY_ACCOUNT")
    }
}
