/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.LocalDate

/**
 * Some prices may vary during a stay, thus here you can see the daily price per period of the stay
 * @property startDate Begin date of the period Format: YYYY-MM-DD 
 * @property endDate End date of the period Format: YYYY-MM-DD 
 * @property base Daily amount excluding tax
 * @property total Daily amount including tax
 */
@JsonClass(generateAdapter = true)
data class PriceVariation(
    @Json(name = "startDate") @field:Json(name = "startDate") var startDate: LocalDate,
    @Json(name = "endDate") @field:Json(name = "endDate") var endDate: LocalDate,
    @Json(name = "base") @field:Json(name = "base") var base: String? = null,
    @Json(name = "total") @field:Json(name = "total") var total: String? = null
)
