/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property currency Currency code of the tax
 * @property amount Amount of the tax
 * @property code The tax code which identifies the tax.   Examples:   1&#x3D;BED_TAX   2&#x3D;CITY_TAX 
 * @property percentage percentage of the tax. Use together with pricingFrequency and pricingMode
 * @property included Is the tax included in the base amount
 * @property description Textual description of the tax
 * @property pricingFrequency Specifies if the tax applies per stay or per night  - PER_STAY  - PER_NIGHT 
 * @property pricingMode Specifies if the tax applies per occupant or per room  - PER_OCCUPANT  - PER_PRODUCT 
 */
@JsonClass(generateAdapter = true)
data class PriceTax(
    @Json(name = "currency") @field:Json(name = "currency") var currency: String? = null,
    @Json(name = "amount") @field:Json(name = "amount") var amount: String? = null,
    @Json(name = "code") @field:Json(name = "code") var code: String? = null,
    @Json(name = "percentage") @field:Json(name = "percentage") var percentage: String? = null,
    @Json(name = "included") @field:Json(name = "included") var included: Boolean? = null,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null,
    @Json(name = "pricingFrequency") @field:Json(name = "pricingFrequency") var pricingFrequency: String? = null,
    @Json(name = "pricingMode") @field:Json(name = "pricingMode") var pricingMode: String? = null
)
