/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Daily price variations and the average daily price (when available) is shown here
 * @property average
 * @property changes A collection of price periods if the daily price changes during the stay
 */
@JsonClass(generateAdapter = true)
data class PriceVariations(
    @Json(name = "average") @field:Json(name = "average") var average: BaseTotalAmount? = null,
    @Json(name = "changes") @field:Json(name = "changes") var changes: List<PriceVariation>? = null
)
