/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * The estimated rate code family of the offer. Grouping various rate plan codes that belongs to the same family and indicates the type of the rate
 * @property code The estimated rate family (PRO,FAM,GOV)
 * @property type The type of the rate (public&#x3D;P, negotiated&#x3D;N, conditional&#x3D;C)
 */
@JsonClass(generateAdapter = true)
data class RateFamily(
    @Json(name = "code") @field:Json(name = "code") var code: String? = null,
    @Json(name = "type") @field:Json(name = "type") var type: String? = null
)
