/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel Booking
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property `data`
 */
@JsonClass(generateAdapter = true)
data class RequestBody(
    @Json(name = "data") @field:Json(name = "data") var `data`: BookinghotelbookingsData
)
