/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property type Room type code, 3 character identifier of the room. The first character identifies the room type category.  The second numeric character identifies the number of beds.  The third character identifies the bed type.  There is a special case where ROH is returned, this value stands for Run Of House. 
 * @property typeEstimated
 * @property description
 */
@JsonClass(generateAdapter = true)
data class RoomDetails(
    @Json(name = "type") @field:Json(name = "type") var type: String? = null,
    @Json(name = "typeEstimated") @field:Json(name = "typeEstimated") var typeEstimated: EstimatedRoomType? = null,
    @Json(name = "description") @field:Json(name = "description") var description: TextWithLanguageType? = null
)
