/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel Ratings
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

/**
 * Integer between 0 and 100. It represents the score for a specific category or the overall rating for a given Hotel.
 */
typealias Score = Int
