/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel Booking
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * Guest Details
 * @property id item identifier
 * @property name
 * @property contact
 * @property hotelRewardsMember Hotel Chain Rewards Member Number. To receive your Rewards Points, access online check in, fast check out. An error is returned by the Chain if the number is invalid. Example Rewards Programs: * Marriott Bonvoy * Hilton Honors * Hyatt Rewards * IHG Rewards * Wyndham Rewards * Accor Live Limitless ALL * Best Western Rewards * Choice Privileges * Radisson Rewards
 */
@JsonClass(generateAdapter = true)
data class Stakeholder(
    @Json(name = "name") @field:Json(name = "name") var name: Name,
    @Json(name = "contact") @field:Json(name = "contact") var contact: Contact,
    @Json(name = "id") @field:Json(name = "id") var id: Int? = null,
    @Json(name = "hotelRewardsMember") @field:Json(name = "hotelRewardsMember") var hotelRewardsMember: String? = null
)
