/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Hotel
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.hotel.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * text and language
 * @property lang Language code of the text ISO language code (https://www.iso.org/iso-639-language-codes.html)
 * @property text Text description
 */
@JsonClass(generateAdapter = true)
data class TextWithLanguageType(
    @Json(name = "lang") @field:Json(name = "lang") var lang: String? = null,
    @Json(name = "text") @field:Json(name = "text") var text: String? = null
)
