/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * identifier of the trip
 * @property number The flight number
 * @property suffix Suffix of the flight number
 */
@JsonClass(generateAdapter = true)
data class AirIdentifier(
    @Json(name = "number") @field:Json(name = "number") var number: String? = null,
    @Json(name = "suffix") @field:Json(name = "suffix") var suffix: String? = null
)
