/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * information of the booking channel
 * @property code Refer to the OTA Booking Channel Type (BCT) codeset list.
 * @property description Booking channel description.
 */
@JsonClass(generateAdapter = true)
data class BookingChannelType(
    @Json(name = "code") @field:Json(name = "code") var code: BookingChannelType.CodeEnum? = null,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null
) {
    /**
     * Refer to the OTA Booking Channel Type (BCT) codeset list.
     * Values: EMA, FAX, N1A, OTH, PHO, WEB, B2B
     */
    @JsonClass(generateAdapter = false)
    enum class CodeEnum(val value: String) {
        @Json(name = "EMA") EMA("EMA"),
        @Json(name = "FAX") FAX("FAX"),
        @Json(name = "N1A") N1A("N1A"),
        @Json(name = "OTH") OTH("OTH"),
        @Json(name = "PHO") PHO("PHO"),
        @Json(name = "WEB") WEB("WEB"),
        @Json(name = "B2B") B2B("B2B")
    }
}
