/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property name
 * @property type media type
 * @property encoding
 * @property size
 * @property src
 * @property ID
 * @property width
 * @property height
 */
@JsonClass(generateAdapter = true)
data class DescriptionMedia(
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "type") @field:Json(name = "type") var type: String? = null,
    @Json(name = "encoding") @field:Json(name = "encoding") var encoding: DescriptionMedia.EncodingEnum? = null,
    @Json(name = "size") @field:Json(name = "size") var size: Int? = null,
    @Json(name = "src") @field:Json(name = "src") var src: String? = null,
    @Json(name = "ID") @field:Json(name = "ID") var ID: String? = null,
    @Json(name = "width") @field:Json(name = "width") var width: Int? = null,
    @Json(name = "height") @field:Json(name = "height") var height: Int? = null
) {
    /**
     * Values: TXT, DOC, GIF, PNG, PDF, JPG, JPEG
     */
    @JsonClass(generateAdapter = false)
    enum class EncodingEnum(val value: String) {
        @Json(name = "TXT") TXT("TXT"),
        @Json(name = "DOC") DOC("DOC"),
        @Json(name = "GIF") GIF("GIF"),
        @Json(name = "PNG") PNG("PNG"),
        @Json(name = "PDF") PDF("PDF"),
        @Json(name = "JPG") JPG("JPG"),
        @Json(name = "JPEG") JPEG("JPEG")
    }
}
