/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property value
 * @property language
 * @property type text type i.e. html, shortDescription
 */
@JsonClass(generateAdapter = true)
data class DescriptionText(
    @Json(name = "value") @field:Json(name = "value") var value: String? = null,
    @Json(name = "language") @field:Json(name = "language") var language: String? = null,
    @Json(name = "type") @field:Json(name = "type") var type: String? = null
)
