/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property texts
 * @property medias
 */
@JsonClass(generateAdapter = true)
data class Description(
    @Json(name = "texts") @field:Json(name = "texts") var texts: List<DescriptionText>? = null,
    @Json(name = "medias") @field:Json(name = "medias") var medias: List<DescriptionMedia>? = null
)
