/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * email information
 * @property category Category of the contact element
 * @property address Email address (e.g. john@smith.com)
 */
@JsonClass(generateAdapter = true)
data class Email(
    @Json(name = "category") @field:Json(name = "category") var category: Email.CategoryEnum? = null,
    @Json(name = "address") @field:Json(name = "address") var address: String? = null
) {
    /**
     * Category of the contact element
     * Values: BUSINESS, PERSONAL, OTHER
     */
    @JsonClass(generateAdapter = false)
    enum class CategoryEnum(val value: String) {
        @Json(name = "BUSINESS") BUSINESS("BUSINESS"),
        @Json(name = "PERSONAL") PERSONAL("PERSONAL"),
        @Json(name = "OTHER") OTHER("OTHER")
    }
}
