/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * information of external system involved
 * @property creation
 * @property bkgReferences The reference of the booking
 */
@JsonClass(generateAdapter = true)
data class ExternalSystemType(
    @Json(name = "creation") @field:Json(name = "creation") var creation: ExternalSystemTypeCreation? = null,
    @Json(name = "bkgReferences") @field:Json(name = "bkgReferences") var bkgReferences: List<ExternalSystemTypeBkgReferences>? = null
)
