/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.ZonedDateTime

/**
 * @property dateTime Booking date in the external system with optional time and time offset
 */
@JsonClass(generateAdapter = true)
data class ExternalSystemTypeCreation(
    @Json(name = "dateTime") @field:Json(name = "dateTime") var dateTime: ZonedDateTime? = null
)
