/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: AI Generated Photos
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property height
 * @property width
 * @property UOM
 */
@JsonClass(generateAdapter = true)
data class FileMediaMetadataDimensions(
    @Json(name = "height") @field:Json(name = "height") var height: Int? = null,
    @Json(name = "width") @field:Json(name = "width") var width: Int? = null,
    @Json(name = "UOM") @field:Json(name = "UOM") var UOM: String? = null
)
