/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: AI Generated Photos
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property application
 * @property caption
 * @property hint
 * @property dimensions
 * @property mediaSource
 */
@JsonClass(generateAdapter = true)
data class FileMediaMetadata(
    @Json(name = "application") @field:Json(name = "application") var application: String? = null,
    @Json(name = "caption") @field:Json(name = "caption") var caption: String? = null,
    @Json(name = "hint") @field:Json(name = "hint") var hint: String? = null,
    @Json(name = "dimensions") @field:Json(name = "dimensions") var dimensions: FileMediaMetadataDimensions? = null,
    @Json(name = "mediaSource") @field:Json(name = "mediaSource") var mediaSource: FileMediaSource? = null
)
