/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: AI Generated Photos
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property code
 * @property version
 * @property filename
 * @property symbology
 * @property copyright
 */
@JsonClass(generateAdapter = true)
data class FileMediaSource(
    @Json(name = "code") @field:Json(name = "code") var code: String? = null,
    @Json(name = "version") @field:Json(name = "version") var version: String? = null,
    @Json(name = "filename") @field:Json(name = "filename") var filename: String? = null,
    @Json(name = "symbology") @field:Json(name = "symbology") var symbology: String? = null,
    @Json(name = "copyright") @field:Json(name = "copyright") var copyright: String? = null
)
