/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Points of Interest
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property latitude latitude of the location
 * @property longitude longitude of the location
 */
@JsonClass(generateAdapter = true)
data class GeoCode(
    @Json(name = "latitude") @field:Json(name = "latitude") var latitude: Double? = null,
    @Json(name = "longitude") @field:Json(name = "longitude") var longitude: Double? = null
)
