/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property href
 * @property methods
 * @property count
 */
@JsonClass(generateAdapter = true)
data class Links(
    @Json(name = "href") @field:Json(name = "href") var href: String,
    @Json(name = "methods") @field:Json(name = "methods") var methods: List<Links.MethodsEnum>? = null,
    @Json(name = "count") @field:Json(name = "count") var count: Int? = null
) {
    /**
     * Values: GET, PUT, DELETE, POST, PATCH
     */
    @JsonClass(generateAdapter = false)
    enum class MethodsEnum(val value: String) {
        @Json(name = "GET") GET("GET"),
        @Json(name = "PUT") PUT("PUT"),
        @Json(name = "DELETE") DELETE("DELETE"),
        @Json(name = "POST") POST("POST"),
        @Json(name = "PATCH") PATCH("PATCH")
    }
}
