/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Points of Interest
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id id of the ressource
 * @property self
 * @property type the resource name
 * @property subType location sub type
 * @property name short name of the location
 * @property geoCode
 * @property category category of the location
 * @property tags list of tags related to the location
 * @property rank the rank is the position compared to other locations based on how famous is a place. 1 being the highest.
 */
@JsonClass(generateAdapter = true)
data class Location(
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "self") @field:Json(name = "self") var self: Links? = null,
    @Json(name = "type") @field:Json(name = "type") var type: String? = null,
    @Json(name = "subType") @field:Json(name = "subType") var subType: Location.SubTypeEnum? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "geoCode") @field:Json(name = "geoCode") var geoCode: GeoCode? = null,
    @Json(name = "category") @field:Json(name = "category") var category: Location.CategoryEnum? = null,
    @Json(name = "tags") @field:Json(name = "tags") var tags: List<String>? = null,
    @Json(name = "rank") @field:Json(name = "rank") var rank: String? = null
) {
    /**
     * location sub type
     * Values: AIRPORT, CITY, POINT_OF_INTEREST
     */
    @JsonClass(generateAdapter = false)
    enum class SubTypeEnum(val value: String) {
        @Json(name = "AIRPORT") AIRPORT("AIRPORT"),
        @Json(name = "CITY") CITY("CITY"),
        @Json(name = "POINT_OF_INTEREST") POINT_OF_INTEREST("POINT_OF_INTEREST")
    }
    /**
     * category of the location
     * Values: SIGHTS, BEACH_PARK, HISTORICAL, NIGHTLIFE, RESTAURANT, SHOPPING
     */
    @JsonClass(generateAdapter = false)
    enum class CategoryEnum(val value: String) {
        @Json(name = "SIGHTS") SIGHTS("SIGHTS"),
        @Json(name = "BEACH_PARK") BEACH_PARK("BEACH_PARK"),
        @Json(name = "HISTORICAL") HISTORICAL("HISTORICAL"),
        @Json(name = "NIGHTLIFE") NIGHTLIFE("NIGHTLIFE"),
        @Json(name = "RESTAURANT") RESTAURANT("RESTAURANT"),
        @Json(name = "SHOPPING") SHOPPING("SHOPPING")
    }
}
