/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: AI Generated Photos
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property type
 * @property id
 * @property self
 * @property owner
 * @property attachmentUri
 * @property description
 * @property fileKbSize
 * @property mediaMetadata
 * @property expirationDateTime expiration time of the attachment uri when applicable Dates and time are specified in the [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) YYYY-MM-DDTHH:MMZ format, e.g. 2019-11-25T22:12Z 
 */
@JsonClass(generateAdapter = true)
data class MediaFile(
    @Json(name = "type") @field:Json(name = "type") var type: String? = null,
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "self") @field:Json(name = "self") var self: Links? = null,
    @Json(name = "owner") @field:Json(name = "owner") var owner: String? = null,
    @Json(name = "attachmentUri") @field:Json(name = "attachmentUri") var attachmentUri: String? = null,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null,
    @Json(name = "fileKbSize") @field:Json(name = "fileKbSize") var fileKbSize: Int? = null,
    @Json(name = "mediaMetadata") @field:Json(name = "mediaMetadata") var mediaMetadata: FileMediaMetadata? = null,
    @Json(name = "expirationDateTime") @field:Json(name = "expirationDateTime") var expirationDateTime: String? = null
)
