/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property id the office id
 * @property cityCode
 * @property countryCode
 * @property regionCode
 */
@JsonClass(generateAdapter = true)
data class Office(
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "cityCode") @field:Json(name = "cityCode") var cityCode: String? = null,
    @Json(name = "countryCode") @field:Json(name = "countryCode") var countryCode: String? = null,
    @Json(name = "regionCode") @field:Json(name = "regionCode") var regionCode: String? = null
)
