/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * information of the originator system
 * @property type Type of the origin system. TripConcierge Manual, Amadeus Integrated Partner, AeTM Web, AeTM Mobile, ePower, eRetail, Sell Classic, Sell Connect, Cros-Sell Notifier, TOMA, IRIS, Other
 * @property description Description of the origin system (notably in case of Other)
 */
@JsonClass(generateAdapter = true)
data class OriginSystemType(
    @Json(name = "type") @field:Json(name = "type") var type: OriginSystemType.TypeEnum? = null,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null
) {
    /**
     * Type of the origin system. TripConcierge Manual, Amadeus Integrated Partner, AeTM Web, AeTM Mobile, ePower, eRetail, Sell Classic, Sell Connect, Cros-Sell Notifier, TOMA, IRIS, Other
     * Values: TRIPCONCIERGE_MANUAL, AMADEUS_INTEGRATED_PARTNER, AETM_WEB, AETM_MOBILE, EPOWER, ERETAIL, SELL_CLASSIC, SELL_CONNECT, CROSSMINUSSELL_NOTIFIER, TOMA, IRIS, B2W, OTHER
     */
    @JsonClass(generateAdapter = false)
    enum class TypeEnum(val value: String) {
        @Json(name = "TRIPCONCIERGE MANUAL") TRIPCONCIERGE_MANUAL("TRIPCONCIERGE MANUAL"),
        @Json(name = "AMADEUS INTEGRATED PARTNER") AMADEUS_INTEGRATED_PARTNER("AMADEUS INTEGRATED PARTNER"),
        @Json(name = "AETM WEB") AETM_WEB("AETM WEB"),
        @Json(name = "AETM MOBILE") AETM_MOBILE("AETM MOBILE"),
        @Json(name = "EPOWER") EPOWER("EPOWER"),
        @Json(name = "ERETAIL") ERETAIL("ERETAIL"),
        @Json(name = "SELL CLASSIC") SELL_CLASSIC("SELL CLASSIC"),
        @Json(name = "SELL CONNECT") SELL_CONNECT("SELL CONNECT"),
        @Json(name = "CROSS-SELL NOTIFIER") CROSSMINUSSELL_NOTIFIER("CROSS-SELL NOTIFIER"),
        @Json(name = "TOMA") TOMA("TOMA"),
        @Json(name = "IRIS") IRIS("IRIS"),
        @Json(name = "B2W") B2W("B2W"),
        @Json(name = "OTHER") OTHER("OTHER")
    }
}
