/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * phone information
 * @property category Category of the contact element
 * @property addresseeName Adressee name (e.g. in case of emergency purpose it corresponds to name of the person to be contacted).
 * @property deviceType
 * @property countryCode Country code of the country (ISO3166-1). E.g. \&quot;US\&quot; for the United States
 * @property countryCallingCode Country calling code of the phone number, as defined by the International Communication Union. Examples - \&quot;1\&quot; for US, \&quot;371\&quot; for Latvia.
 * @property areaCode Corresponds to a regional code or a city code. The length of the field varies depending on the area.
 * @property number Phone number. Composed of digits only. The number of digits depends on the country.
 * @property extension Extension of the phone
 * @property text String containing the full phone number - applicable only when a structured phone (i.e. countryCallingCode + number) is not provided
 */
@JsonClass(generateAdapter = true)
data class Phone(
    @Json(name = "category") @field:Json(name = "category") var category: Phone.CategoryEnum? = null,
    @Json(name = "addresseeName") @field:Json(name = "addresseeName") var addresseeName: String? = null,
    @Json(name = "deviceType") @field:Json(name = "deviceType") var deviceType: PhoneDeviceType? = null,
    @Json(name = "countryCode") @field:Json(name = "countryCode") var countryCode: String? = null,
    @Json(name = "countryCallingCode") @field:Json(name = "countryCallingCode") var countryCallingCode: String? = null,
    @Json(name = "areaCode") @field:Json(name = "areaCode") var areaCode: String? = null,
    @Json(name = "number") @field:Json(name = "number") var number: String? = null,
    @Json(name = "extension") @field:Json(name = "extension") var extension: String? = null,
    @Json(name = "text") @field:Json(name = "text") var text: String? = null
) {
    /**
     * Category of the contact element
     * Values: BUSINESS, PERSONAL, OTHER
     */
    @JsonClass(generateAdapter = false)
    enum class CategoryEnum(val value: String) {
        @Json(name = "BUSINESS") BUSINESS("BUSINESS"),
        @Json(name = "PERSONAL") PERSONAL("PERSONAL"),
        @Json(name = "OTHER") OTHER("OTHER")
    }
}
