/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Purpose Prediction
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
* forecast description
* Values: BUSINESS,LEISURE
*/
@JsonClass(generateAdapter = false)
enum class PredictionResultType(val value: String) {
    @Json(name = "BUSINESS") BUSINESS("BUSINESS"),
    @Json(name = "LEISURE") LEISURE("LEISURE")
}
