/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * guarantee information
 * @property paymentForm Form of Payment to guarantee the booking. Authorized forms of payment for Guarantee are 1-Credit Card, 10-Travel Agent identification, ID-Customer ID, 6-Check, 4-MCO, 12-Company Name. 
 * @property paymentDetails Payment details
 */
@JsonClass(generateAdapter = true)
data class ProductHotelGuarantee(
    @Json(name = "paymentForm") @field:Json(name = "paymentForm") var paymentForm: ProductHotelGuarantee.PaymentFormEnum? = null,
    @Json(name = "paymentDetails") @field:Json(name = "paymentDetails") var paymentDetails: String? = null
) {
    /**
     * Form of Payment to guarantee the booking. Authorized forms of payment for Guarantee are 1-Credit Card, 10-Travel Agent identification, ID-Customer ID, 6-Check, 4-MCO, 12-Company Name. 
     * Values: _1, _10, ID, _6, _4, _12
     */
    @JsonClass(generateAdapter = false)
    enum class PaymentFormEnum(val value: String) {
        @Json(name = "1") _1("1"),
        @Json(name = "10") _10("10"),
        @Json(name = "ID") ID("ID"),
        @Json(name = "6") _6("6"),
        @Json(name = "4") _4("4"),
        @Json(name = "12") _12("12")
    }
}
