/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * distance of the trip
 * @property distance Distance of the trip
 * @property unit Unit of distance, in kilometers (KM) or miles (MI)
 */
@JsonClass(generateAdapter = true)
data class ProductMoveMiscMileage(
    @Json(name = "distance") @field:Json(name = "distance") var distance: Int? = null,
    @Json(name = "unit") @field:Json(name = "unit") var unit: ProductMoveMiscMileage.UnitEnum? = null
) {
    /**
     * Unit of distance, in kilometers (KM) or miles (MI)
     * Values: KM, MI
     */
    @JsonClass(generateAdapter = false)
    enum class UnitEnum(val value: String) {
        @Json(name = "KM") KM("KM"),
        @Json(name = "MI") MI("MI")
    }
}
