/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property bkgChannel
 * @property originSystem It is calculated automatically. If filled, the input will be discarded for the calculated value.
 * @property externalSystem
 * @property creation
 * @property modification
 * @property confirmation
 * @property descriptions
 */
@JsonClass(generateAdapter = true)
data class ProductCommon(
    @Json(name = "bkgChannel") @field:Json(name = "bkgChannel") var bkgChannel: BookingChannelType? = null,
    @Json(name = "originSystem") @field:Json(name = "originSystem") var originSystem: OriginSystemType? = null,
    @Json(name = "externalSystem") @field:Json(name = "externalSystem") var externalSystem: ExternalSystemType? = null,
    @Json(name = "creation") @field:Json(name = "creation") var creation: ProductCreation? = null,
    @Json(name = "modification") @field:Json(name = "modification") var modification: ProductModification? = null,
    @Json(name = "confirmation") @field:Json(name = "confirmation") var confirmation: ProductConfirmation? = null,
    @Json(name = "descriptions") @field:Json(name = "descriptions") var descriptions: List<Description>? = null
)
