/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * used to convey all information about the rate
 * @property category The RateCategory attribute defines a set of valid values for the category of a rate. Typically rates are offered as either Leisure rates or Business (Corporate) rates, with a business rate usually including additional costs such as the cost of insurance, etc.  This set of values defines the rate categories. 
 * @property code Car rental company&#39;s code for the rate.
 * @property description Rate code description.
 */
@JsonClass(generateAdapter = true)
data class ProductCarConditionsRate(
    @Json(name = "category") @field:Json(name = "category") var category: ProductCarConditionsRate.CategoryEnum? = null,
    @Json(name = "code") @field:Json(name = "code") var code: String? = null,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null
) {
    /**
     * The RateCategory attribute defines a set of valid values for the category of a rate. Typically rates are offered as either Leisure rates or Business (Corporate) rates, with a business rate usually including additional costs such as the cost of insurance, etc.  This set of values defines the rate categories. 
     * Values: ASSOCIATION, BUSINESS, CONVENTION, CONSORTIUM, CORPORATE, CREDENTIAL, GENERAL, GOVERNMENT, INCLUSIVE, INDUSTRY, LEISURE_MINUS_PACKAGE, STANDARD
     */
    @JsonClass(generateAdapter = false)
    enum class CategoryEnum(val value: String) {
        @Json(name = "ASSOCIATION") ASSOCIATION("ASSOCIATION"),
        @Json(name = "BUSINESS") BUSINESS("BUSINESS"),
        @Json(name = "CONVENTION") CONVENTION("CONVENTION"),
        @Json(name = "CONSORTIUM") CONSORTIUM("CONSORTIUM"),
        @Json(name = "CORPORATE") CORPORATE("CORPORATE"),
        @Json(name = "CREDENTIAL") CREDENTIAL("CREDENTIAL"),
        @Json(name = "GENERAL") GENERAL("GENERAL"),
        @Json(name = "GOVERNMENT") GOVERNMENT("GOVERNMENT"),
        @Json(name = "INCLUSIVE") INCLUSIVE("INCLUSIVE"),
        @Json(name = "INDUSTRY") INDUSTRY("INDUSTRY"),
        @Json(name = "LEISURE - PACKAGE") LEISURE_MINUS_PACKAGE("LEISURE - PACKAGE"),
        @Json(name = "STANDARD") STANDARD("STANDARD")
    }
}
