/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property code Train Station code, can be UIC code (with type&#x3D;UIC or other value) or closest IATA code (with no type)
 * @property type
 * @property name Name of the departure point
 */
@JsonClass(generateAdapter = true)
data class ProductTrainLocation(
    @Json(name = "code") @field:Json(name = "code") var code: String,
    @Json(name = "type") @field:Json(name = "type") var type: String? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null
)
