/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property number Number of children
 * @property age Age of children
 * @property ageCode Age code (specific to hotel property)
 */
@JsonClass(generateAdapter = true)
data class ProductHotelCustomersChildren(
    @Json(name = "number") @field:Json(name = "number") var number: Int? = null,
    @Json(name = "age") @field:Json(name = "age") var age: Int? = null,
    @Json(name = "ageCode") @field:Json(name = "ageCode") var ageCode: String? = null
)
