/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property phone pick-up location phone information
 */
@JsonClass(generateAdapter = true)
data class ProductCarContact(
    @Json(name = "phone") @field:Json(name = "phone") var phone: String? = null
)
