/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.LocalDate

/**
 * @property dateTime check-out date (service date) in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format, e.g. 2017-02-10T20:40:00+02:00 - Only date is stored for Hotel in this attribute
 */
@JsonClass(generateAdapter = true)
data class ProductHotelEnd(
    @Json(name = "dateTime") @field:Json(name = "dateTime") var dateTime: LocalDate
)
