/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.ZonedDateTime

/**
 * air Reservation
 * @property bkgChannel
 * @property originSystem It is calculated automatically. If filled, the input will be discarded for the calculated value.
 * @property externalSystem
 * @property creation
 * @property modification
 * @property confirmation
 * @property descriptions
 * @property description Description or Free text
 * @property bkgClass Booking Class
 * @property status Status code (example HK, HX, HN, HL, TT ...)
 * @property NIP Number in party
 * @property agreement Airline alliance, group information
 * @property ruleNumber Rule number required by some providers to complete the booking
 * @property confirmNbr Confirmation number
 * @property cancelNbr Cancellation number
 * @property overrideStatus Enable to override status code (ex. for Offers)
 * @property MBOProductCode Freetext on twenty characters, sub-product of the MBO (Ex. For EC AIR &gt; international, domestic, european)
 * @property serviceProvider
 * @property identifier
 * @property partnerInfo
 * @property start
 * @property end
 * @property seats
 * @property vehicle
 * @property meal
 * @property duration Duration of the trip
 * @property mileage
 * @property baggages Baggages information
 * @property checkInEndTime Check-in information
 * @property ticket
 * @property cabinClass Category code of the cabin. F &#x3D; First, C &#x3D; Club (Business), W &#x3D; Premium Economy, Y &#x3D; Economy.
 * @property routeId Route Id
 */
@JsonClass(generateAdapter = true)
data class ProductAir(
    @Json(name = "bkgChannel") @field:Json(name = "bkgChannel") var bkgChannel: BookingChannelType? = null,
    @Json(name = "originSystem") @field:Json(name = "originSystem") var originSystem: OriginSystemType? = null,
    @Json(name = "externalSystem") @field:Json(name = "externalSystem") var externalSystem: ExternalSystemType? = null,
    @Json(name = "creation") @field:Json(name = "creation") var creation: ProductCreation? = null,
    @Json(name = "modification") @field:Json(name = "modification") var modification: ProductModification? = null,
    @Json(name = "confirmation") @field:Json(name = "confirmation") var confirmation: ProductConfirmation? = null,
    @Json(name = "descriptions") @field:Json(name = "descriptions") var descriptions: List<Description>? = null,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null,
    @Json(name = "bkgClass") @field:Json(name = "bkgClass") var bkgClass: String? = null,
    @Json(name = "status") @field:Json(name = "status") var status: String? = null,
    @Json(name = "NIP") @field:Json(name = "NIP") var NIP: Int? = null,
    @Json(name = "agreement") @field:Json(name = "agreement") var agreement: String? = null,
    @Json(name = "ruleNumber") @field:Json(name = "ruleNumber") var ruleNumber: String? = null,
    @Json(name = "confirmNbr") @field:Json(name = "confirmNbr") var confirmNbr: String? = null,
    @Json(name = "cancelNbr") @field:Json(name = "cancelNbr") var cancelNbr: String? = null,
    @Json(name = "overrideStatus") @field:Json(name = "overrideStatus") var overrideStatus: String? = null,
    @Json(name = "MBOProductCode") @field:Json(name = "MBOProductCode") var MBOProductCode: String? = null,
    @Json(name = "serviceProvider") @field:Json(name = "serviceProvider") var serviceProvider: ProductAirServiceProvider1? = null,
    @Json(name = "identifier") @field:Json(name = "identifier") var identifier: AirIdentifier? = null,
    @Json(name = "partnerInfo") @field:Json(name = "partnerInfo") var partnerInfo: ProductAirPartnerInfo? = null,
    @Json(name = "start") @field:Json(name = "start") var start: ProductAirStart? = null,
    @Json(name = "end") @field:Json(name = "end") var end: ProductAirEnd? = null,
    @Json(name = "seats") @field:Json(name = "seats") var seats: List<ProductAirSeat>? = null,
    @Json(name = "vehicle") @field:Json(name = "vehicle") var vehicle: ProductAirVehicle? = null,
    @Json(name = "meal") @field:Json(name = "meal") var meal: ProductAirMeal? = null,
    @Json(name = "duration") @field:Json(name = "duration") var duration: String? = null,
    @Json(name = "mileage") @field:Json(name = "mileage") var mileage: ProductAirMileage? = null,
    @Json(name = "baggages") @field:Json(name = "baggages") var baggages: List<ProductAirBaggages>? = null,
    @Json(name = "checkInEndTime") @field:Json(name = "checkInEndTime") var checkInEndTime: ZonedDateTime? = null,
    @Json(name = "ticket") @field:Json(name = "ticket") var ticket: ProductAirTicket? = null,
    @Json(name = "cabinClass") @field:Json(name = "cabinClass") var cabinClass: String? = null,
    @Json(name = "routeId") @field:Json(name = "routeId") var routeId: String? = null
)
