/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.ZonedDateTime

/**
 * used to convey the pick-up information (pick-up date, time, location, ...) of the car booking
 * @property dateTime Drop-off date with optional time and time offset in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format, e.g. 2017-02-10T20:40:00+02:00
 * @property providerLocationCode Used to specify a non airport Location Code for pick-up. This code should be unique to clearly identify the location.
 * @property locationCodes Drop-off location code, can be an IATA code ([IATA table codes](http://www.iata.org/publications/Pages/code-search.aspx)), a provider location code (type&#x3D;CPY) or an amadeus location code (type&#x3D;AMA)
 * @property address
 * @property contact
 * @property media
 */
@JsonClass(generateAdapter = true)
data class ProductCarEnd(
    @Json(name = "dateTime") @field:Json(name = "dateTime") var dateTime: ZonedDateTime? = null,
    @Json(name = "providerLocationCode") @field:Json(name = "providerLocationCode") var providerLocationCode: String? = null,
    @Json(name = "locationCodes") @field:Json(name = "locationCodes") var locationCodes: List<ProductCarLocationCode>? = null,
    @Json(name = "address") @field:Json(name = "address") var address: Address? = null,
    @Json(name = "contact") @field:Json(name = "contact") var contact: ProductCarContact? = null,
    @Json(name = "media") @field:Json(name = "media") var media: Relationship? = null
)
