/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.ZonedDateTime

/**
 * used to convey the pick-up information (pick-up date, time, location, ...) of the car booking
 * @property dateTime Arrival date with optional time and time offset in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format, e.g. 2017-02-10T20:40:00+02:00
 * @property location
 * @property platform Reference of the arrival platform
 */
@JsonClass(generateAdapter = true)
data class ProductTrainEnd(
    @Json(name = "dateTime") @field:Json(name = "dateTime") var dateTime: ZonedDateTime? = null,
    @Json(name = "location") @field:Json(name = "location") var location: ProductTrainLocation? = null,
    @Json(name = "platform") @field:Json(name = "platform") var platform: String? = null
)
