/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.LocalDate

/**
 * Ticket information
 * @property number Ticket number
 * @property issuanceDate Ticket issuance date
 */
@JsonClass(generateAdapter = true)
data class ProductAirTicket(
    @Json(name = "number") @field:Json(name = "number") var number: String? = null,
    @Json(name = "issuanceDate") @field:Json(name = "issuanceDate") var issuanceDate: LocalDate? = null
)
