/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.ZonedDateTime

/**
 * @property dateTime Departure date (Service date) with optional time and time offset in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format, e.g. 2017-02-10T20:40:00+02:00
 * @property terminal Departure terminal
 * @property locationCode [IATA table codes](http://www.iata.org/publications/Pages/code-search.aspx) of the departure location
 * @property address
 * @property media
 */
@JsonClass(generateAdapter = true)
data class ProductMoveMiscStart(
    @Json(name = "dateTime") @field:Json(name = "dateTime") var dateTime: ZonedDateTime,
    @Json(name = "terminal") @field:Json(name = "terminal") var terminal: String? = null,
    @Json(name = "locationCode") @field:Json(name = "locationCode") var locationCode: String? = null,
    @Json(name = "address") @field:Json(name = "address") var address: Address? = null,
    @Json(name = "media") @field:Json(name = "media") var media: Relationship? = null
)
