/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.ZonedDateTime

/**
 * hotel reservation
 * @property bkgChannel
 * @property originSystem It is calculated automatically. If filled, the input will be discarded for the calculated value.
 * @property externalSystem
 * @property creation
 * @property modification
 * @property confirmation
 * @property descriptions
 * @property description Description or Free text
 * @property bkgClass Room categories are U-Unknown, B-Budget , T-Standard, S-Superior, X-Deluxe, E-Executive, J-Junior Suite, D-Suite standard, I-Suite Deluxe. Temporary solution waiting to define Room as real elements linked to the ETR Hotel and Pax. 
 * @property accomodationType Room type (U-Unknown, S-Single, D-Double, R-Triple, Y-Family Room).
 * @property bedType Bed type.
 * @property bedNumber Number of beds.
 * @property amenities List amenities available in the property.
 * @property status Status code (example HK, HX, HN, HL, TT ...)
 * @property NIP Number in party
 * @property additionalServices This attribute indicates the additional services that have been requested by the Travel Agent. Additional services are services booked on top of the room (generally meal -breakfast, fullboard- or extra bed-crib, ...). 
 * @property cancelPolicies Cancellation policy.
 * @property otherRules Other rules.
 * @property confirmNbr Confirmation number
 * @property cancelNbr Cancellation number
 * @property overrideStatus Enable to override status code (ex. for Offers)
 * @property MBOProductCode Freetext on twenty characters, sub-product of the MBO (Ex. For EC AIR &gt; international, domestic, european)
 * @property serviceProvider
 * @property chain
 * @property start
 * @property end
 * @property checkInEndTime Check-in time (indicates the expected time limit from when the guests can arrive at the property on check-in day) -  Only time is stored for Hotel in this attribute. Time respects ISO 8601 standard.  e.g. 13:22:00+01:00   
 * @property checkOutEndTime Check-out time (indicates the time limit when the guests should leave the property on check-out day) - Only time is stored for Hotel in this attribute. Time respects ISO 8601 standard.  e.g. 13:22:00+01:00  
 * @property customers
 * @property mealPlan Dining option 
 * @property guarantee
 * @property deposit
 * @property rate
 * @property codes
 */
@JsonClass(generateAdapter = true)
data class ProductHotel(
    @Json(name = "start") @field:Json(name = "start") var start: ProductHotelStart,
    @Json(name = "checkInEndTime") @field:Json(name = "checkInEndTime") var checkInEndTime: ZonedDateTime,
    @Json(name = "checkOutEndTime") @field:Json(name = "checkOutEndTime") var checkOutEndTime: ZonedDateTime,
    @Json(name = "bkgChannel") @field:Json(name = "bkgChannel") var bkgChannel: BookingChannelType? = null,
    @Json(name = "originSystem") @field:Json(name = "originSystem") var originSystem: OriginSystemType? = null,
    @Json(name = "externalSystem") @field:Json(name = "externalSystem") var externalSystem: ExternalSystemType? = null,
    @Json(name = "creation") @field:Json(name = "creation") var creation: ProductCreation? = null,
    @Json(name = "modification") @field:Json(name = "modification") var modification: ProductModification? = null,
    @Json(name = "confirmation") @field:Json(name = "confirmation") var confirmation: ProductConfirmation? = null,
    @Json(name = "descriptions") @field:Json(name = "descriptions") var descriptions: List<Description>? = null,
    @Json(name = "description") @field:Json(name = "description") var description: String? = null,
    @Json(name = "bkgClass") @field:Json(name = "bkgClass") var bkgClass: String? = null,
    @Json(name = "accomodationType") @field:Json(name = "accomodationType") var accomodationType: String? = null,
    @Json(name = "bedType") @field:Json(name = "bedType") var bedType: String? = null,
    @Json(name = "bedNumber") @field:Json(name = "bedNumber") var bedNumber: Int? = null,
    @Json(name = "amenities") @field:Json(name = "amenities") var amenities: String? = null,
    @Json(name = "status") @field:Json(name = "status") var status: String? = null,
    @Json(name = "NIP") @field:Json(name = "NIP") var NIP: Int? = null,
    @Json(name = "additionalServices") @field:Json(name = "additionalServices") var additionalServices: String? = null,
    @Json(name = "cancelPolicies") @field:Json(name = "cancelPolicies") var cancelPolicies: String? = null,
    @Json(name = "otherRules") @field:Json(name = "otherRules") var otherRules: String? = null,
    @Json(name = "confirmNbr") @field:Json(name = "confirmNbr") var confirmNbr: String? = null,
    @Json(name = "cancelNbr") @field:Json(name = "cancelNbr") var cancelNbr: String? = null,
    @Json(name = "overrideStatus") @field:Json(name = "overrideStatus") var overrideStatus: String? = null,
    @Json(name = "MBOProductCode") @field:Json(name = "MBOProductCode") var MBOProductCode: String? = null,
    @Json(name = "serviceProvider") @field:Json(name = "serviceProvider") var serviceProvider: ProductHotelServiceProvider? = null,
    @Json(name = "chain") @field:Json(name = "chain") var chain: ProductHotelChain? = null,
    @Json(name = "end") @field:Json(name = "end") var end: ProductHotelEnd? = null,
    @Json(name = "customers") @field:Json(name = "customers") var customers: ProductHotelCustomers? = null,
    @Json(name = "mealPlan") @field:Json(name = "mealPlan") var mealPlan: String? = null,
    @Json(name = "guarantee") @field:Json(name = "guarantee") var guarantee: ProductHotelGuarantee? = null,
    @Json(name = "deposit") @field:Json(name = "deposit") var deposit: ProductHotelDesposit? = null,
    @Json(name = "rate") @field:Json(name = "rate") var rate: ProductHotelRate? = null,
    @Json(name = "codes") @field:Json(name = "codes") var codes: List<ProductHotelCode>? = null
)
