/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property air
 * @property hotel
 * @property moveMiscellaneous
 * @property car
 * @property train
 */
@JsonClass(generateAdapter = true)
data class Product(
    @Json(name = "air") @field:Json(name = "air") var air: ProductAir? = null,
    @Json(name = "hotel") @field:Json(name = "hotel") var hotel: ProductHotel? = null,
    @Json(name = "moveMiscellaneous") @field:Json(name = "moveMiscellaneous") var moveMiscellaneous: ProductMoveMisc? = null,
    @Json(name = "car") @field:Json(name = "car") var car: ProductCar? = null,
    @Json(name = "train") @field:Json(name = "train") var train: ProductTrain? = null
)
