/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property rate
 * @property mileageLimitation
 */
@JsonClass(generateAdapter = true)
data class ProductCarConditions(
    @Json(name = "rate") @field:Json(name = "rate") var rate: ProductCarConditionsRate? = null,
    @Json(name = "mileageLimitation") @field:Json(name = "mileageLimitation") var mileageLimitation: ProductCarConditionsMileageLimitation? = null
)
