/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.ZonedDateTime

/**
 * end point details
 * @property dateTime End date with optional time and time offset in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format, e.g. 2017-02-10T20:40:00+02:00
 * @property terminal Arrival terminal
 * @property locationName Name of the arrival city
 * @property airportName Name of the arrival Airport
 * @property visaAlert Indicator to define if a visa is needed for the arrival country (True) or not (False)
 * @property cityCode Code of the arrival city
 * @property countryCode Code of the arrival country
 * @property locationCode [IATA table codes](http://www.iata.org/publications/Pages/code-search.aspx) of the arrival location
 * @property address
 * @property media
 */
@JsonClass(generateAdapter = true)
data class ProductAirEnd(
    @Json(name = "locationCode") @field:Json(name = "locationCode") var locationCode: String,
    @Json(name = "dateTime") @field:Json(name = "dateTime") var dateTime: ZonedDateTime? = null,
    @Json(name = "terminal") @field:Json(name = "terminal") var terminal: String? = null,
    @Json(name = "locationName") @field:Json(name = "locationName") var locationName: String? = null,
    @Json(name = "airportName") @field:Json(name = "airportName") var airportName: String? = null,
    @Json(name = "visaAlert") @field:Json(name = "visaAlert") var visaAlert: Boolean? = null,
    @Json(name = "cityCode") @field:Json(name = "cityCode") var cityCode: String? = null,
    @Json(name = "countryCode") @field:Json(name = "countryCode") var countryCode: String? = null,
    @Json(name = "address") @field:Json(name = "address") var address: Address? = null,
    @Json(name = "media") @field:Json(name = "media") var media: Relationship? = null
)
