/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * marketing service provider information
 * @property ref The provider&#39;s profile reference
 * @property code Marketing Airline code
 * @property name Provider name
 * @property baggagePolicyLink Link to the provider baggage policy
 * @property isTLA To-Do
 */
@JsonClass(generateAdapter = true)
data class ProductAirServiceProvider(
    @Json(name = "ref") @field:Json(name = "ref") var ref: String? = null,
    @Json(name = "code") @field:Json(name = "code") var code: String? = null,
    @Json(name = "name") @field:Json(name = "name") var name: String? = null,
    @Json(name = "baggagePolicyLink") @field:Json(name = "baggagePolicyLink") var baggagePolicyLink: String? = null,
    @Json(name = "isTLA") @field:Json(name = "isTLA") var isTLA: Boolean? = null
)
