/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * description of the guests (number of adults, number of children by age)
 * @property adults Number of adults.
 * @property children Number of children (with the age in attribute).
 */
@JsonClass(generateAdapter = true)
data class ProductHotelCustomers(
    @Json(name = "adults") @field:Json(name = "adults") var adults: Int? = null,
    @Json(name = "children") @field:Json(name = "children") var children: List<ProductHotelCustomersChildren>? = null
)
