/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Purpose Prediction
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property type the resource name (&#x60;prediction&#x60;)
 * @property subType
 * @property id item identifier
 * @property result
 * @property probability probability of the forecast (between 0 and 1)
 */
@JsonClass(generateAdapter = true)
data class PurposePrediction(
    @Json(name = "type") @field:Json(name = "type") var type: String? = null,
    @Json(name = "subType") @field:Json(name = "subType") var subType: String? = null,
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "result") @field:Json(name = "result") var result: PredictionResultType? = null,
    @Json(name = "probability") @field:Json(name = "probability") var probability: String? = null
)
