/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: AI Generated Photos
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property type
 * @property id
 * @property self
 */
@JsonClass(generateAdapter = true)
data class Resource(
    @Json(name = "type") @field:Json(name = "type") var type: String? = null,
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "self") @field:Json(name = "self") var self: Links? = null
)
