/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * details on the travel agency owning the trip
 * @property officeName Office name of the travel agency
 * @property phone Phone number of the travel agency
 * @property email Email of the travel agency
 * @property address adress of the travel agency
 */
@JsonClass(generateAdapter = true)
data class TravelAgency(
    @Json(name = "officeName") @field:Json(name = "officeName") var officeName: String? = null,
    @Json(name = "phone") @field:Json(name = "phone") var phone: Phone? = null,
    @Json(name = "email") @field:Json(name = "email") var email: Email? = null,
    @Json(name = "address") @field:Json(name = "address") var address: Address? = null
)
