/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property type the resource name
 * @property id item identifier
 * @property status
 * @property detail
 * @property result
 * @property self
 */
@JsonClass(generateAdapter = true)
data class TripParserJobOut(
    @Json(name = "type") @field:Json(name = "type") var type: String,
    @Json(name = "status") @field:Json(name = "status") var status: TripParserJobOut.StatusEnum,
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "detail") @field:Json(name = "detail") var detail: String? = null,
    @Json(name = "result") @field:Json(name = "result") var result: Relationship? = null,
    @Json(name = "self") @field:Json(name = "self") var self: Links? = null
) {
    /**
     * Values: STARTED, IN_PROGRESS, COMPLETED, FAILED
     */
    @JsonClass(generateAdapter = false)
    enum class StatusEnum(val value: String) {
        @Json(name = "STARTED") STARTED("STARTED"),
        @Json(name = "IN_PROGRESS") IN_PROGRESS("IN_PROGRESS"),
        @Json(name = "COMPLETED") COMPLETED("COMPLETED"),
        @Json(name = "FAILED") FAILED("FAILED")
    }
}
