/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import org.threeten.bp.ZonedDateTime

/**
 * @property dateTime Date of the stop with optional time and time offset in [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) format, e.g. 2017-02-10T20:40:00+02:00
 * @property locationName Name of the stop city
 * @property duration duration of the stop
 * @property locationCode Stop Location [IATA code](https://en.wikipedia.org/wiki/International_Air_Transport_Association_airport_code)
 * @property address
 */
@JsonClass(generateAdapter = true)
data class TripStep(
    @Json(name = "dateTime") @field:Json(name = "dateTime") var dateTime: ZonedDateTime? = null,
    @Json(name = "locationName") @field:Json(name = "locationName") var locationName: String? = null,
    @Json(name = "duration") @field:Json(name = "duration") var duration: String? = null,
    @Json(name = "locationCode") @field:Json(name = "locationCode") var locationCode: String? = null,
    @Json(name = "address") @field:Json(name = "address") var address: Address? = null
)
