/**
 * NOTE: This class is auto generated by the Swagger Gradle Codegen for the following API: Trip Parser
 *
 * More info on this tool is available on https://github.com/Yelp/swagger-gradle-codegen
 */

package com.amadeus.android.domain.trip.models

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * @property type the resource name
 * @property id item identifier
 * @property content content of the travel email in base64 format. To be present only as input in case of post operation.
 * @property self
 */
@JsonClass(generateAdapter = true)
data class TripParserJobIn(
    @Json(name = "type") @field:Json(name = "type") var type: String,
    @Json(name = "content") @field:Json(name = "content") var content: String,
    @Json(name = "id") @field:Json(name = "id") var id: String? = null,
    @Json(name = "self") @field:Json(name = "self") var self: Links? = null
)
