name: Publish
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  publish:
    name: Release build and publish
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        cache: gradle
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: clean
      run: ./gradlew clean
    - name: Build
      run: ./gradlew build -x test
    - name: Unit Test 
      run: ./gradlew testDebugUnitTest --tests 'com.amadeus.android.unit*'
    - name: Maven Local
      run: ./gradlew publishToMavenLocal
    - name: Decode
      run: |
        echo "${{secrets.SIGN_KEYFILE}}" > ~/.gradle/secring.gpg.b64
        base64 -d ~/.gradle/secring.gpg.b64 > ~/.gradle/secring.gpg
    - name: Publish
      run: ./gradlew publish --no-daemon --no-parallel -Psigning.keyId=${{secrets.SIGN_KEYID}} -Psigning.password=${{secrets.SIGN_PASSWORD}} -Psigning.secretKeyRingFile=$(echo ~/.gradle/secring.gpg)
      env:
        OSSRH_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
        OSSRH_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
